"""ION Kernel package.

Keep exports lazy so package initialization does not eagerly import submodules that may
also be invoked as entrypoints.
"""

from importlib import import_module
from typing import Any

_EXPORT_MODULES = {
    "SelfSurfaceDriftSignal": ".self_surface_drift_gate",
    "SelfSurfaceDriftAssessment": ".self_surface_drift_gate",
    "assess_self_surface_text": ".self_surface_drift_gate",
    "validate_self_surface_drift_assessment": ".self_surface_drift_gate",
    "write_self_surface_drift_assessment": ".self_surface_drift_gate",
    "AgentSuccessionPacket": ".agent_succession_packet",
    "AgentSuccessionPacketReceipt": ".agent_succession_packet",
    "generate_agent_succession_packet": ".agent_succession_packet",
    "validate_agent_succession_packet": ".agent_succession_packet",
    "write_agent_succession_packet": ".agent_succession_packet",
    "SelfMountGraphNode": ".self_mount_graph_integration",
    "SelfMountGraphEdge": ".self_mount_graph_integration",
    "SelfMountGraphProjection": ".self_mount_graph_integration",
    "generate_self_mount_graph_projection": ".self_mount_graph_integration",
    "validate_self_mount_graph_projection": ".self_mount_graph_integration",
    "write_self_mount_graph_projection": ".self_mount_graph_integration",
    "RuntimeIdentityEnvelope": ".runtime_identity_envelope",
    "RuntimeIdentityEnvelopeReceipt": ".runtime_identity_envelope",
    "RuntimeIdentityEnvelopeReport": ".runtime_identity_envelope",
    "generate_runtime_identity_envelope": ".runtime_identity_envelope",
    "validate_runtime_identity_envelope": ".runtime_identity_envelope",
    "bind_runtime_identity_envelope": ".runtime_identity_envelope",
    "generate_runtime_identity_envelope_report": ".runtime_identity_envelope",
    "write_runtime_identity_envelope": ".runtime_identity_envelope",
    "write_runtime_identity_envelope_receipt": ".runtime_identity_envelope",
    "write_runtime_identity_envelope_report": ".runtime_identity_envelope",
    "format_runtime_identity_envelope_summary": ".runtime_identity_envelope",
    "MountedAgentIdentity": ".agent_self_surface",
    "AgentSelfSurfaceReport": ".agent_self_surface",
    "generate_gpt55_mounted_identity": ".agent_self_surface",
    "validate_mounted_identity": ".agent_self_surface",
    "generate_agent_self_surface_report": ".agent_self_surface",
    "write_agent_self_surface_report": ".agent_self_surface",
    "format_agent_self_surface_summary": ".agent_self_surface",
    "RatificationRow": ".production_readiness",
    "ProductionReadinessReport": ".production_readiness",
    "generate_production_readiness_report": ".production_readiness",
    "write_production_readiness_report": ".production_readiness",
    "format_production_readiness_summary": ".production_readiness",
    "SummaryRefreshDemoReleaseCandidateVerification": ".summary_refresh_demo_release_candidate_verify",
    "SummaryRefreshDemoReleaseCandidateVerificationError": ".summary_refresh_demo_release_candidate_verify",
    "verify_summary_refresh_demo_release_candidate": ".summary_refresh_demo_release_candidate_verify",
    "resolve_release_candidate_dir": ".summary_refresh_demo_release_candidate_verify",
    "verify_checksum_file": ".summary_refresh_demo_release_candidate_verify",
    "write_release_candidate_verification_report": ".summary_refresh_demo_release_candidate_verify",
    "format_release_candidate_verification_summary": ".summary_refresh_demo_release_candidate_verify",
    "SummaryRefreshDemoReleaseCandidate": ".summary_refresh_demo_release_candidate",
    "SummaryRefreshDemoReleaseCandidateError": ".summary_refresh_demo_release_candidate",
    "create_summary_refresh_demo_release_candidate": ".summary_refresh_demo_release_candidate",
    "write_release_candidate_manifest": ".summary_refresh_demo_release_candidate",
    "write_release_candidate_commands": ".summary_refresh_demo_release_candidate",
    "write_release_candidate_readme": ".summary_refresh_demo_release_candidate",
    "write_release_candidate_checksums": ".summary_refresh_demo_release_candidate",
    "format_release_candidate_summary": ".summary_refresh_demo_release_candidate",
    "SummaryRefreshDemoEvidenceBundle": ".summary_refresh_demo_evidence_bundle",
    "SummaryRefreshDemoEvidenceBundleError": ".summary_refresh_demo_evidence_bundle",
    "create_summary_refresh_demo_evidence_bundle": ".summary_refresh_demo_evidence_bundle",
    "write_evidence_bundle_manifest": ".summary_refresh_demo_evidence_bundle",
    "write_evidence_bundle_readme": ".summary_refresh_demo_evidence_bundle",
    "format_evidence_bundle_summary": ".summary_refresh_demo_evidence_bundle",
    "SummaryRefreshDemoCertificationReport": ".summary_refresh_demo_certification",
    "certify_summary_refresh_demo": ".summary_refresh_demo_certification",
    "write_certification_report": ".summary_refresh_demo_certification",
    "format_certification_summary": ".summary_refresh_demo_certification",
    "SummaryRefreshDemoReplayDoctorReport": ".summary_refresh_demo_doctor",
    "DemoReplayDoctorModeResult": ".summary_refresh_demo_doctor",
    "run_summary_refresh_demo_doctor": ".summary_refresh_demo_doctor",
    "write_doctor_report": ".summary_refresh_demo_doctor",
    "format_doctor_summary": ".summary_refresh_demo_doctor",
    "SummaryRefreshDemoReplayReport": ".summary_refresh_demo_replay",
    "run_summary_refresh_demo_replay": ".summary_refresh_demo_replay",
    "write_replay_report": ".summary_refresh_demo_replay",
    "format_replay_summary": ".summary_refresh_demo_replay",
    "SummaryRefreshDemoRunner": ".summary_refresh_demo",
    "IonSummaryRefreshDemoRunner": ".summary_refresh_demo",
    "SummaryRefreshDemoResult": ".summary_refresh_demo",
    "FrontDoorRuntimeGateway": ".front_door_runtime_entry",
    "IonFrontDoorRuntimeGateway": ".front_door_runtime_entry",
    "FrontDoorRuntimeEntryError": ".front_door_runtime_entry",
    "FrontDoorBoundaryStage": ".front_door_runtime_entry",
    "FrontDoorReceiptStatus": ".front_door_runtime_entry",
    "PersonaInterfaceIngress": ".front_door_runtime_entry",
    "RelaySemanticBoundaryPacket": ".front_door_runtime_entry",
    "StewardRoutingEnvelope": ".front_door_runtime_entry",
    "RelayReturnPackage": ".front_door_runtime_entry",
    "PersonaResponsePackage": ".front_door_runtime_entry",
    "FrontDoorRuntimeReceipt": ".front_door_runtime_entry",
    "FrontDoorIngressResult": ".front_door_runtime_entry",
    "FrontDoorReturnResult": ".front_door_runtime_entry",
    "format_front_door_self_mount_binding_summary": ".front_door_self_mount_binding",
    "write_front_door_self_mount_binding_receipt": ".front_door_self_mount_binding",
    "write_front_door_self_mount_binding": ".front_door_self_mount_binding",
    "validate_front_door_self_mount_binding": ".front_door_self_mount_binding",
    "bind_front_door_self_mount": ".front_door_self_mount_binding",
    "FrontDoorSelfMountBindingResult": ".front_door_self_mount_binding",
    "FrontDoorSelfMountBindingReceipt": ".front_door_self_mount_binding",
    "FrontDoorSelfMountBinding": ".front_door_self_mount_binding",
    "FrontDoorChatOrchestrationAdapter": ".front_door_chat_orchestration",
    "IonFrontDoorChatOrchestrationAdapter": ".front_door_chat_orchestration",
    "FrontDoorChatTurnResult": ".front_door_chat_orchestration",
    "FrontDoorChatReturnResult": ".front_door_chat_orchestration",
    "ExecutionBundle": ".sequential_kernel",
    "LoadTarget": ".sequential_kernel",
    "RoleConfig": ".sequential_kernel",
    "RolePass": ".sequential_kernel",
    "RoleSession": ".sequential_kernel",
    "SequentialKernelRouter": ".sequential_kernel",
    "SequentialTrace": ".sequential_kernel",
    "TaskRetirement": ".sequential_kernel",
    "Workstream": ".sequential_kernel",
    "default_repo_root": ".sequential_kernel",
    "KernelOperatorCliError": ".operator_cli",
    "main": ".operator_cli",
    "find_session_path": ".sequential_kernel",
    "record_bundle_session_update": ".sequential_kernel",
    "record_session_update": ".sequential_kernel",
    "retire_task_packet": ".sequential_kernel",
    "write_execution_bundle": ".sequential_kernel",
    "write_trace_artifact": ".sequential_kernel",
    "AgentIdentity": ".model",
    "ArtifactOperation": ".model",
    "AuthorityClass": ".model",
    "ChildAgentBinding": ".children",
    "ChildSpec": ".model",
    "ChildWorkIssuancePreparation": ".children",
    "ChildWorkIssuanceResult": ".children",
    "CommitDelta": ".model",
    "PlannerIntentType": ".model",
    "PlannerManifest": ".model",
    "PlannerManifestStatus": ".model",
    "PlannerManifestSweepReceipt": ".model",
    "PlannerManifestSweepAggregateRecord": ".model",
    "ManifestModeBinding": ".model",
    "ManifestRouteStateRecord": ".model",
    "RouteBranch": ".model",
    "RouteFrame": ".model",
    "RouteOwnerScope": ".model",
    "RoutingAssessment": ".model",
    "EvidencePressure": ".model",
    "AutomationGate": ".model",
    "AutomationStateRecord": ".model",
    "HorizonLayer": ".model",
    "HorizonWorkItem": ".model",
    "HorizonRecord": ".model",
    "HorizonEnactmentReceipt": ".model",
    "ScheduleSourceKind": ".model",
    "ScheduleCommitment": ".model",
    "ScheduleState": ".model",
    "ScheduleCarrier": ".model",
    "CarrierBindingSource": ".model",
    "BranchClaimStatus": ".model",
    "BranchSettlementOutcome": ".model",
    "ExecutorTrustClass": ".model",
    "ExecutorAvailability": ".model",
    "FallbackSuitability": ".model",
    "ExecutorCapability": ".model",
    "ExecutorWorkLifecycleBindingReceipt": ".model",
    "ScheduleReceipt": ".model",
    "ScheduleControlReceipt": ".model",
    "ScheduleCompletionReleaseReceipt": ".model",
    "ScheduleSettlementReceipt": ".model",
    "ScheduleLineageArchiveReceipt": ".model",
    "ScheduleLineageReplayReceipt": ".model",
    "ScheduleResumeProjectionReceipt": ".model",
    "ScheduleResumeBundleMaterializationReceipt": ".model",
    "ScheduleTakeoverEntryActivationReceipt": ".model",
    "ScheduleActivationHandoffCapsuleReceipt": ".model",
    "ScheduleHandoffEntryRehearsalReceipt": ".model",
    "ScheduleExecutorStartPacketMaterializationReceipt": ".model",
    "TakeoverAssessmentReceipt": ".model",
    "ManualAutomationEquivalenceReceipt": ".model",
    "ContinuationReadWitness": ".model",
    "ContextPerfectContinuationReceipt": ".model",
    "BranchClaimReceipt": ".model",
    "BranchControlReceipt": ".model",
    "BranchMergeProposal": ".model",
    "BranchSettlementReceipt": ".model",
    "BranchHorizonSyncReceipt": ".model",
    "BranchRescheduleReceipt": ".model",
    "QuestionAnswerRecord": ".model",
    "ReviewerAnswerQueueProjectionRecord": ".model",
    "ReviewerQueueRefreshReceipt": ".model",
    "CommitDeltaStatus": ".model",
    "CanonicalSignalType": ".receipts",
    "DaemonActionCandidate": ".daemon",
    "DaemonActionType": ".daemon",
    "DaemonArbitrationResult": ".daemon",
    "DaemonActOnceResult": ".daemon_actions",
    "DaemonActOnceStatus": ".daemon_actions",
    "DaemonLoopResult": ".daemon_loop",
    "DaemonLoopStatus": ".daemon_loop",
    "ReviewEscalationPreparation": ".reviews",
    "ReviewEscalationResult": ".reviews",
    "ContextCompileRequest": ".context_compiler",
    "ContextCompilerError": ".context_compiler",
    "ContextPackage": ".model",
    "ContextTiers": ".model",
    "DependencyInterface": ".model",
    "DispatchPacket": ".dispatch",
    "DispatchPreparation": ".dispatch",
    "DispatchResult": ".dispatch",
    "CommitApplication": ".commit",
    "CommitApplicationResult": ".commit",
    "ExecutionPreparation": ".execution",
    "ExecutionResult": ".execution",
    "VisualDiagnosisFinding": ".visual_diagnosis_receipt",
    "VisualDiagnosisAction": ".visual_diagnosis_receipt",
    "BrowserHarnessPlan": ".visual_diagnosis_receipt",
    "VisualDiagnosisReceipt": ".visual_diagnosis_receipt",
    "make_visual_diagnosis_finding": ".visual_diagnosis_receipt",
    "make_visual_diagnosis_action": ".visual_diagnosis_receipt",
    "build_browser_harness_plan": ".visual_diagnosis_receipt",
    "build_visual_diagnosis_receipt": ".visual_diagnosis_receipt",
    "validate_visual_diagnosis_receipt": ".visual_diagnosis_receipt",
    "write_visual_diagnosis_receipt": ".visual_diagnosis_receipt",
    "format_visual_diagnosis_summary": ".visual_diagnosis_receipt",
    "ExecutionSubmission": ".execution",
    "GraphEdge": ".graph",
    "GraphEdgeType": ".graph",
    "InputRef": ".model",
    "InputRefType": ".model",
    "InputVisibility": ".model",
    "IonDaemonActuator": ".daemon_actions",
    "IonDaemonLoop": ".daemon_loop",
    "IonChildWorkIssuer": ".children",
    "IonDaemonArbiter": ".daemon",
    "IonGraph": ".graph",
    "IonDispatcher": ".dispatch",
    "IonExecutor": ".execution",
    "IonCommitApplier": ".commit",
    "IonQuestionRouter": ".questions",
    "IonQuestionAnswerIngestor": ".question_answers",
    "IonPlannerChildIssuanceGate": ".planner_gate",
    "IonReceiptEmitter": ".receipts",
    "IonReviewEscalator": ".reviews",
    "IonSignalConsumer": ".signals",
    "IonSignalFollowUpHandler": ".signal_followups",
    "IonSignalInterpreter": ".signals",
    "IonValidator": ".validation",
    "IonScheduler": ".scheduler",
    "KernelCommitApplier": ".commit",
    "KernelCommitError": ".commit",
    "KernelChildWorkIssuer": ".children",
    "KernelChildWorkIssuanceError": ".children",
    "KernelDaemonActionError": ".daemon_actions",
    "KernelDaemonActuator": ".daemon_actions",
    "KernelDaemonArbiter": ".daemon",
    "KernelDaemonLoop": ".daemon_loop",
    "KernelDaemonLoopError": ".daemon_loop",
    "KernelQuestionRouter": ".questions",
    "KernelQuestionAnswerError": ".question_answers",
    "KernelQuestionAnswerIngestor": ".question_answers",
    "KernelQuestionAnswerProjectionBuilder": ".question_answers",
    "KernelPlannerChildIssuanceGate": ".planner_gate",
    "KernelPlannerGateError": ".planner_gate",
    "KernelQuestionRoutingError": ".questions",
    "KernelReceiptEmitter": ".receipts",
    "KernelReceiptError": ".receipts",
    "KernelReviewEscalationError": ".reviews",
    "KernelReviewEscalator": ".reviews",
    "KernelSignalConsumer": ".signals",
    "KernelSignalConsumerError": ".signals",
    "KernelSignalFollowUpError": ".signal_followups",
    "KernelSignalFollowUpHandler": ".signal_followups",
    "KernelSignalInterpreter": ".signals",
    "KernelExecutionError": ".execution",
    "KernelRecord": ".model",
    "KernelDispatchError": ".dispatch",
    "KernelGraph": ".graph",
    "KernelExecutor": ".execution",
    "KernelDispatcher": ".dispatch",
    "KernelValidationError": ".validation",
    "KernelValidator": ".validation",
    "KernelScheduler": ".scheduler",
    "KernelSchedulerError": ".scheduler",
    "ArbitrationPolicySurface": ".scheduler",
    "ScheduleCandidate": ".scheduler",
    "ScheduleProjection": ".scheduler",
    "KernelExecutorCapabilityRegistry": ".executor_registry",
    "KernelExecutorCapabilityError": ".executor_registry",
    "ExecutorCapabilitySelection": ".executor_registry",
    "ExecutorCapabilitySnapshot": ".executor_registry",
    "KernelTakeoverManager": ".takeover",
    "KernelTakeoverError": ".takeover",
    "takeover_assessment_receipt_id": ".takeover",
    "render_takeover_assessment": ".takeover",
    "KernelManualAutomationEquivalenceManager": ".equivalence",
    "KernelManualAutomationEquivalenceError": ".equivalence",
    "manual_automation_equivalence_receipt_id": ".equivalence",
    "KernelBootstrapInitError": ".bootstrap_init",
    "KernelBootstrapInitWriter": ".bootstrap_init",
    "IonBootstrapInitWriter": ".bootstrap_init",
    "KernelBootstrapSignalBridge": ".bootstrap_bridge",
    "IonBootstrapSignalBridge": ".bootstrap_bridge",
    "KernelBootstrapActivationError": ".bootstrap_activation",
    "KernelBootstrapActivationManager": ".bootstrap_activation",
    "IonBootstrapActivationManager": ".bootstrap_activation",
    "KernelAuthorityLineageManager": ".authority_lineage",
    "IonAuthorityLineageManager": ".authority_lineage",
    "KernelAuthorityLineageError": ".authority_lineage",
    "AuthorityResolution": ".authority_lineage",
    "AuthorityAuditFinding": ".authority_lineage",
    "AuthorityAuditReport": ".authority_lineage",
    "AuthorityNameRecord": ".authority_lineage",
    "AuthoritySurfaceRecord": ".authority_lineage",
    "AuthorityRegistryAlignmentFinding": ".authority_lineage",
    "AuthorityRegistryAlignmentReport": ".authority_lineage",
    "KernelContextPerfectContinuationManager": ".continuation",
    "IonContextPerfectContinuationManager": ".continuation",
    "KernelContextPerfectContinuationError": ".continuation",
    "context_perfect_continuation_receipt_id": ".continuation",
    "KernelAllocator": ".allocator",
    "KernelAllocatorError": ".allocator",
    "branch_allocation_id": ".allocator",
    "branch_claim_receipt_id": ".allocator",
    "KernelBranchControlManager": ".branch_controls",
    "KernelBranchControlError": ".branch_controls",
    "branch_control_receipt_id": ".branch_controls",
    "KernelBranchSettlementManager": ".settlement",
    "KernelBranchHorizonSynchronizer": ".branch_horizon_sync",
    "KernelBranchRescheduler": ".branch_rescheduling",
    "KernelScheduleControlManager": ".schedule_controls",
    "KernelScheduleDispatchReconciliationManager": ".schedule_dispatch_reconciliation",
    "KernelScheduleCompletionReleaseManager": ".schedule_completion_release",
    "KernelScheduleSettlementManager": ".schedule_settlement",
    "KernelScheduleLineageArchiveManager": ".schedule_lineage",
    "KernelScheduleLineageReplayManager": ".schedule_lineage_replay",
    "KernelScheduleResumeProjectionManager": ".schedule_resume_projection",
    "KernelScheduleResumeBundleMaterializationManager": ".schedule_resume_bundle",
    "IonScheduleResumeBundleMaterializationManager": ".schedule_resume_bundle",
    "KernelScheduleTakeoverActivationManager": ".schedule_takeover_activation",
    "IonScheduleTakeoverEntryActivationManager": ".schedule_takeover_activation",
    "KernelScheduleActivationHandoffCapsuleManager": ".schedule_handoff_capsule",
    "KernelScheduleHandoffEntryRehearsalManager": ".schedule_handoff_entry_rehearsal",
    "KernelScheduleExecutorStartPacketManager": ".schedule_executor_start_packet",
    "KernelScheduleHandoffEntryRehearsalError": ".schedule_handoff_entry_rehearsal",
    "schedule_handoff_entry_rehearsal_receipt_id": ".schedule_handoff_entry_rehearsal",
    "KernelScheduleExecutorStartPacketError": ".schedule_executor_start_packet",
    "schedule_executor_start_packet_materialization_receipt_id": ".schedule_executor_start_packet",
    "KernelScheduleActivationHandoffCapsuleError": ".schedule_handoff_capsule",
    "schedule_activation_handoff_capsule_receipt_id": ".schedule_handoff_capsule",
    "KernelScheduleTakeoverActivationError": ".schedule_takeover_activation",
    "schedule_takeover_entry_activation_receipt_id": ".schedule_takeover_activation",
    "KernelScheduleResumeBundleMaterializationError": ".schedule_resume_bundle",
    "schedule_resume_bundle_materialization_receipt_id": ".schedule_resume_bundle",
    "KernelBranchSettlementError": ".settlement",
    "branch_settlement_receipt_id": ".settlement",
    "branch_merge_proposal_id": ".settlement",
    "LedgerEntry": ".model",
    "OpenQuestion": ".model",
    "OpenQuestionPriority": ".model",
    "OpenQuestionStatus": ".model",
    "ParsedQuestionDirective": ".questions",
    "PriorFinding": ".model",
    "PreparedChildWork": ".children",
    "ProducedArtifact": ".model",
    "ProposedSignal": ".model",
    "ReceiptEmissionResult": ".receipts",
    "ReceiptPreparation": ".receipts",
    "SignalLifecycleStatus": ".receipts",
    "SignalConsumptionResult": ".signals",
    "SignalExpirationResult": ".signals",
    "SignalFileRef": ".signals",
    "SignalFollowUpDisposition": ".signal_followups",
    "SignalFollowUpPreparation": ".signal_followups",
    "SignalFollowUpResult": ".signal_followups",
    "SignalInterpretation": ".signals",
    "SignalInterpretationResult": ".signals",
    "SignalMeaning": ".signals",
    "SignalRecommendedAction": ".signals",
    "SIGNAL_FOLLOWUP_DOMAIN": ".signal_followups",
    "QuestionResolutionResult": ".questions",
    "QuestionAnswerSubmission": ".question_answers",
    "QuestionAnswerProjection": ".question_answers",
    "ReviewerAnswerQueue": ".question_answers",
    "ReviewerAnswerQueueProjectionResult": ".question_answers",
    "ReviewerQueueRefreshSweepResult": ".question_answers",
    "reviewer_queue_projection_id": ".question_answers",
    "reviewer_queue_refresh_receipt_id": ".question_answers",
    "KernelQuestionAnswerProjectionBuilder": ".question_answers",
    "IonQuestionAnswerProjectionBuilder": ".question_answers",
    "QuestionAnswerPreparation": ".question_answers",
    "QuestionAnswerResult": ".question_answers",
    "ReviewerQueueRefreshCandidate": ".question_answers",
    "ReviewerQueueRefreshResult": ".question_answers",
    "planner_manifest_id": ".planner_gate",
    "PlannerManifestPreparation": ".planner_gate",
    "PlannerManifestCompileCandidate": ".planner_gate",
    "PlannerManifestMaintenanceCandidate": ".planner_gate",
    "PlannerManifestResult": ".planner_gate",
    "PlannerManifestSweepResult": ".planner_gate",
    "PlannerManifestSweepAggregateResult": ".planner_gate",
    "planner_manifest_sweep_receipt_id": ".planner_gate",
    "planner_manifest_sweep_aggregate_id": ".planner_gate",
    "PlannerChildIssuancePreparation": ".planner_gate",
    "PlannerChildIssuanceResult": ".planner_gate",
    "QuestionRoutingPreparation": ".questions",
    "QuestionRoutingResult": ".questions",
    "REVIEW_DOMAIN": ".reviews",
    "ValidationReceipt": ".receipts",
    "EmittedSignal": ".receipts",
    "ScheduleReason": ".scheduler",
    "schedule_receipt_id": ".scheduler",
    "ScopeType": ".model",
    "SemanticOverlay": ".model",
    "SpawnPolicy": ".model",
    "StateMutation": ".model",
    "StateMutationOperation": ".model",
    "StrEnum": ".model",
    "TargetFile": ".model",
    "TierFiveDependencies": ".model",
    "TierFourSemantic": ".model",
    "TierOneDoctrine": ".model",
    "TierThreeMission": ".model",
    "TierTwoTarget": ".model",
    "ValidationDecision": ".validation",
    "WorkPriority": ".model",
    "WorkUnitDispatchAssessment": ".scheduler",
    "WorkUnit": ".model",
    "WorkUnitStatus": ".model",
    "IonIndex": ".index",
    "IonStore": ".store",
    "KernelIndex": ".index",
    "KernelStore": ".store",
    "RuntimeSessionStore": ".runtime_session_store",
    "IonRuntimeSessionStore": ".runtime_session_store",
    "ApiRuntimeEntryGateway": ".api_runtime_entry",
    "IonApiRuntimeEntryGateway": ".api_runtime_entry",
    "ApiRuntimeEntryError": ".api_runtime_entry",
    "ApiRuntimeEntryIntent": ".api_runtime_entry",
    "ApiRuntimeEntryReceipt": ".api_runtime_entry",
    "ApiRuntimeEntryResult": ".api_runtime_entry",
    "ApiRuntimeEntryStatus": ".api_runtime_entry",
    "ApiCarrierBoundary": ".api_runtime_entry",
    "RuntimeEntryFailureDisposition": ".api_runtime_entry",
    "FleetLifecycleStore": ".fleet_lifecycle_store",
    "FleetLifecycleStoreError": ".fleet_lifecycle_store",
    "FleetIdentity": ".fleet_lifecycle_store",
    "FleetMemberIdentity": ".fleet_lifecycle_store",
    "FleetMemberState": ".fleet_lifecycle_store",
    "FleetEvent": ".fleet_lifecycle_store",
    "FleetReceipt": ".fleet_lifecycle_store",
    "FleetExecutorCapabilityBinder": ".fleet_executor_capability_binding",
    "FleetExecutorWorkEntryResult": ".fleet_executor_work_lifecycle_binding",
    "FleetExecutorWorkLifecycleBindingError": ".fleet_executor_work_lifecycle_binding",
    "FleetExecutorWorkLifecycleBinder": ".fleet_executor_work_lifecycle_binding",
    "FleetExecutorWorkClosureBinder": ".fleet_executor_work_closure_binding",
    "FleetExecutorWorkClosureBindingError": ".fleet_executor_work_closure_binding",
    "FleetExecutorWorkClosureResult": ".fleet_executor_work_closure_binding",
    "FleetCapabilityBindingError": ".fleet_executor_capability_binding",
    "FleetCapabilitySyncReceipt": ".fleet_executor_capability_binding",
    "RuntimeSessionQueueDispatcher": ".runtime_session_dispatch_binding",
    "IonRuntimeSessionQueueDispatcher": ".runtime_session_dispatch_binding",
    "RuntimeSessionQueueDispatchResult": ".runtime_session_dispatch_binding",
    "RuntimeSessionDispatchBindingError": ".runtime_session_dispatch_binding",
    "RuntimeSessionStoreError": ".runtime_session_store",
    "RuntimeSessionIdentity": ".runtime_session_store",
    "RuntimeSessionAuthority": ".runtime_session_store",
    "RuntimeSessionCarrierBinding": ".runtime_session_store",
    "RuntimeSessionContextBinding": ".runtime_session_store",
    "RuntimeSessionReceipt": ".runtime_session_store",
    "RuntimeSessionEvent": ".runtime_session_store",
    "RuntimeSessionLifecycleState": ".runtime_session_store",
    "RuntimeCarrierKind": ".runtime_session_store",
    "SessionQueueItemStatus": ".runtime_session_store",
    "SessionQueue": ".runtime_session_store",
    "SessionQueueItem": ".runtime_session_store",
    "KernelStoreError": ".store",
    "compile_context_package": ".context_compiler",
    "IonCompileContextPackage": ".context_compiler",
    "compile_context_package_for_work_unit": ".context_compiler",
    "IonCompileContextPackageForWorkUnit": ".context_compiler",
    "render_dispatch_packet": ".dispatch",
    "render_context_package_text": ".context_compiler",
    "IonRenderContextPackageText": ".context_compiler",
    "write_dispatch_packet": ".dispatch",
    "AutomationStage": ".threshold",
    "AutomationActionClass": ".automation_policy",
    "AutomationPolicyDecision": ".automation_policy",
    "AutomationPolicyEvaluation": ".automation_policy",
    "AutomationPolicyRequest": ".automation_policy",
    "CalibrationStatus": ".threshold",
    "ContextMode": ".threshold",
    "GovernedWriteReceipt": ".governed_write",
    "GovernedWriteRequest": ".governed_write",
    "GovernedWriteStageResult": ".governed_write",
    "KernelCapsuleError": ".capsule_manager",
    "KernelCapsuleManager": ".capsule_manager",
    "CapsuleDriftCheckResult": ".capsule_manager",
    "CapsuleRecord": ".capsule_manager",
    "KernelGovernedWriteError": ".governed_write",
    "KernelGovernedWriter": ".governed_write",
    "KernelThresholdError": ".threshold",
    "KernelThresholdEvaluator": ".threshold",
    "PromotionAction": ".threshold",
    "RouteStage": ".threshold",
    "ThresholdCondition": ".threshold",
    "ThresholdEvaluation": ".threshold",
    "ThresholdHit": ".threshold",
    "ThresholdOperator": ".threshold",
    "ThresholdSnapshot": ".threshold",
    "IonCapsuleManager": ".capsule_manager",
    "IonGovernedWriter": ".governed_write",
    "IonThresholdEvaluator": ".threshold",
    "KernelAutomationPolicy": ".automation_policy",
    "IonAutomationPolicy": ".automation_policy",
    "KernelHorizonStateError": ".horizon_state",
    "KernelHorizonStateManager": ".horizon_state",
    "horizon_enactment_receipt_id": ".horizon_state",
    "HorizonStatePreparation": ".horizon_state",
    "HorizonStateResult": ".horizon_state",
    "HorizonScopeSummary": ".horizon_state",
    "HorizonTighteningResult": ".horizon_state",
    "HorizonPacketEnactmentResult": ".horizon_state",
    "IonHorizonStateManager": ".horizon_state",
    "horizon_record_id": ".horizon_state",
    "KernelPacketValidationError": ".packet_validation",
    "PacketValidationMessage": ".packet_validation",
    "WorkflowPacketRule": ".packet_validation",
    "PacketValidationResult": ".packet_validation",
    "ParsedWorkflowPacket": ".packet_validation",
    "PacketTakeoverAssessment": ".packet_validation",
    "workflow_packet_types": ".packet_validation",
    "validate_packet_path": ".packet_validation",
    "validate_packet_text": ".packet_validation",
    "render_packet_validation": ".packet_validation",
    "parse_workflow_packet_path": ".packet_validation",
    "parse_workflow_packet_text": ".packet_validation",
    "assess_packet_takeover_path": ".packet_validation",
    "assess_packet_takeover_text": ".packet_validation",
    "render_takeover_role_session": ".packet_validation",
    "KernelChildWorkServiceError": ".child_work_service",
    "KernelChildWorkService": ".child_work_service",
    "ChildWorkSelectionMode": ".child_work_service",
    "ChildWorkServiceStatus": ".child_work_service",
    "ChildWorkServiceRequest": ".child_work_service",
    "ChildWorkServiceReceipt": ".child_work_service",
    "IonChildWorkService": ".child_work_service",
    "KernelOperatorControlError": ".operator_control",
    "KernelOperatorControlManager": ".operator_control",
    "DaemonServiceControlMode": ".operator_control",
    "ScopeHold": ".operator_control",
    "OperatorControlState": ".operator_control",
    "OperatorControlMutationResult": ".operator_control",
    "IonOperatorControlManager": ".operator_control",
    "KernelOperationalHardeningError": ".operational_hardening",
    "KernelOperationalHardeningManager": ".operational_hardening",
    "OperationalAcceptanceChecklistReceipt": ".operational_hardening",
    "OperationalAcceptanceCriterion": ".operational_hardening",
    "OperationalRunbookReceipt": ".operational_hardening",
    "SupervisedRuntimeLifecycleReceipt": ".operational_hardening",
    "SupervisedRuntimeLifecycleStatus": ".operational_hardening",
    "SupervisedRuntimeShutdownRequest": ".operational_hardening",
    "SupervisedRuntimeStartupRequest": ".operational_hardening",
    "SupervisedRuntimeStatusSnapshot": ".operational_hardening",
    "IonOperationalHardeningManager": ".operational_hardening",
    "KernelDaemonServiceError": ".daemon_service",
    "KernelDaemonService": ".daemon_service",
    "KernelExternalExecutionBridgeError": ".external_execution_bridge",
    "KernelExternalExecutionBridge": ".external_execution_bridge",
    "ExternalExecutionActionMode": ".external_execution_bridge",
    "ExternalExecutionBridgeStatus": ".external_execution_bridge",
    "ExternalExecutionBridgeRequest": ".external_execution_bridge",
    "ExternalExecutionBridgeReceipt": ".external_execution_bridge",
    "MCPAutomationSurface": ".external_execution_bridge",
    "IonExternalExecutionBridge": ".external_execution_bridge",
    "DaemonServiceRequest": ".daemon_service",
    "DaemonServiceStatus": ".daemon_service",
    "DaemonServiceRecoveryState": ".daemon_service",
    "DaemonServiceReceipt": ".daemon_service",
    "IonDaemonService": ".daemon_service",
    "KernelRecoveryReplayError": ".recovery_replay",
    "KernelRecoveryReplayManager": ".recovery_replay",
    "RecoveryReplaySelectionMode": ".recovery_replay",
    "RecoveryReplayStatus": ".recovery_replay",
    "RecoveryReplayRequest": ".recovery_replay",
    "RecoveryReplayReceipt": ".recovery_replay",
    "ServiceRecoveryClassification": ".recovery_replay",
    "IonRecoveryReplayManager": ".recovery_replay",
    "KernelRuntimeStateSync": ".runtime_state_sync",
    "RuntimeStateSyncResult": ".runtime_state_sync",
    "IonRuntimeStateSync": ".runtime_state_sync",
    "KernelManifestRouteStateError": ".manifest_state",
    "KernelManifestRouteStateManager": ".manifest_state",
    "ManifestRouteStatePreparation": ".manifest_state",
    "ManifestRouteStateResult": ".manifest_state",
    "manifest_route_state_id": ".manifest_state",
    "IonManifestRouteStateManager": ".manifest_state",
    "KernelAutomationStateError": ".automation_state",
    "KernelAutomationStateManager": ".automation_state",
    "AutomationStatePreparation": ".automation_state",
    "AutomationStateResult": ".automation_state",
    "automation_state_record_id": ".automation_state",
    "IonAutomationStateManager": ".automation_state",
    "KernelRuntimeStateView": ".runtime_state_views",
    "RuntimeStateScopeView": ".runtime_state_views",
    "RuntimeReviewPressure": ".runtime_state_views",
    "RuntimeDispatchPosture": ".runtime_state_views",
    "IonRuntimeStateView": ".runtime_state_views",
    "KernelRuntimeReportArtifactError": ".runtime_report_artifacts",
    "KernelRuntimeReportArtifactEmitter": ".runtime_report_artifacts",
    "RuntimeReportArtifactKind": ".runtime_report_artifacts",
    "RuntimeReportArtifact": ".runtime_report_artifacts",
    "RuntimeReportArtifactPreparation": ".runtime_report_artifacts",
    "RuntimeReportArtifactResult": ".runtime_report_artifacts",
    "IonRuntimeReportArtifactEmitter": ".runtime_report_artifacts",
    "KernelRuntimeReportingError": ".runtime_reporting",
    "KernelRuntimeStateReporter": ".runtime_reporting",
    "RuntimeScopeStatusBundle": ".runtime_reporting",
    "IonRuntimeStateReporter": ".runtime_reporting",
    "KernelRuntimeReportTriggerError": ".runtime_report_triggers",
    "KernelRuntimeReportTriggerManager": ".runtime_report_triggers",
    "RuntimeReportTriggerEvent": ".runtime_report_triggers",
    "RuntimeReportTriggerRequest": ".runtime_report_triggers",
    "RuntimeReportTriggerReceipt": ".runtime_report_triggers",
    "IonRuntimeReportTriggerManager": ".runtime_report_triggers",
    "KernelRuntimeReportGovernanceError": ".runtime_report_governance",
    "KernelRuntimeReportGovernanceManager": ".runtime_report_governance",
    "RuntimeReportGovernanceBatchResult": ".runtime_report_governance",
    "IonRuntimeReportGovernanceManager": ".runtime_report_governance",
    "KernelRuntimeReportGovernanceAggregationError": ".runtime_report_governance_aggregation",
    "KernelRuntimeReportGovernanceAggregationManager": ".runtime_report_governance_aggregation",
    "RuntimeReportGovernanceAggregationBatchResult": ".runtime_report_governance_aggregation",
    "IonRuntimeReportGovernanceAggregationManager": ".runtime_report_governance_aggregation",
    "KernelRuntimeReportVisibilityError": ".runtime_report_visibility",
    "KernelRuntimeReportVisibilityProjector": ".runtime_report_visibility",
    "RuntimeReportVisibilityBatchResult": ".runtime_report_visibility",
    "IonRuntimeReportVisibilityProjector": ".runtime_report_visibility",
    "KernelRuntimeReportNavigationError": ".runtime_report_navigation",
    "KernelRuntimeReportNavigator": ".runtime_report_navigation",
    "RuntimeReportNavigationQuery": ".runtime_report_navigation",
    "RuntimeReportNavigationEntry": ".runtime_report_navigation",
    "RuntimeReportNavigationResult": ".runtime_report_navigation",
    "IonRuntimeReportNavigator": ".runtime_report_navigation",
    "KernelRuntimeReportBrowserError": ".runtime_report_browser",
    "KernelRuntimeReportBrowser": ".runtime_report_browser",
    "RuntimeReportBrowserFacetCounts": ".runtime_report_browser",
    "RuntimeReportBrowserResult": ".runtime_report_browser",
    "RuntimeReportBrowserWriteResult": ".runtime_report_browser",
    "IonRuntimeReportBrowser": ".runtime_report_browser",
    "artifact_anchor": ".runtime_report_anchors",
    "dashboard_entry_anchor": ".runtime_report_anchors",
    "governance_summary_anchor": ".runtime_report_anchors",
    "operator_rollup_anchor": ".runtime_report_anchors",
    "packet_index_pointer": ".runtime_report_anchors",
    "ledger_row_pointer": ".runtime_report_anchors",
    "anchor_tag": ".runtime_report_anchors",
    "KernelRuntimeReportCrosslinkError": ".runtime_report_crosslinks",
    "KernelRuntimeReportCrosslinker": ".runtime_report_crosslinks",
    "RuntimeReportCrosslinkTarget": ".runtime_report_crosslinks",
    "RuntimeReportCrosslinkedEntry": ".runtime_report_crosslinks",
    "RuntimeReportCrosslinkView": ".runtime_report_crosslinks",
    "RuntimeReportCrosslinkWriteResult": ".runtime_report_crosslinks",
    "IonRuntimeReportCrosslinker": ".runtime_report_crosslinks",
    "KernelRuntimeReportProvenanceError": ".runtime_report_provenance",
    "KernelRuntimeReportProvenanceTracer": ".runtime_report_provenance",
    "RuntimeReportProvenanceSelector": ".runtime_report_provenance",
    "RuntimeReportProvenanceTarget": ".runtime_report_provenance",
    "RuntimeReportProvenanceLayer": ".runtime_report_provenance",
    "RuntimeReportProvenanceTrace": ".runtime_report_provenance",
    "RuntimeReportProvenanceWriteResult": ".runtime_report_provenance",
    "IonRuntimeReportProvenanceTracer": ".runtime_report_provenance",
    "KernelRuntimeReportComparativeProvenanceError": ".runtime_report_comparative_provenance",
    "KernelRuntimeReportComparativeProvenanceTracer": ".runtime_report_comparative_provenance",
    "RuntimeReportComparativeSelector": ".runtime_report_comparative_provenance",
    "RuntimeReportComparativeReceipt": ".runtime_report_comparative_provenance",
    "RuntimeReportComparativeLayerReceipt": ".runtime_report_comparative_provenance",
    "RuntimeReportComparativeLayer": ".runtime_report_comparative_provenance",
    "RuntimeReportComparativeTrace": ".runtime_report_comparative_provenance",
    "RuntimeReportComparativeWriteResult": ".runtime_report_comparative_provenance",
    "IonRuntimeReportComparativeProvenanceTracer": ".runtime_report_comparative_provenance",
    "KernelRuntimeReportTemporalProvenanceError": ".runtime_report_temporal_provenance",
    "KernelRuntimeReportTemporalProvenanceTracer": ".runtime_report_temporal_provenance",
    "RuntimeReportTemporalSelector": ".runtime_report_temporal_provenance",
    "RuntimeReportTemporalGeneration": ".runtime_report_temporal_provenance",
    "RuntimeReportTemporalLayerGeneration": ".runtime_report_temporal_provenance",
    "RuntimeReportTemporalLayerTransition": ".runtime_report_temporal_provenance",
    "RuntimeReportTemporalLayer": ".runtime_report_temporal_provenance",
    "RuntimeReportTemporalTrace": ".runtime_report_temporal_provenance",
    "RuntimeReportTemporalWriteResult": ".runtime_report_temporal_provenance",
    "IonRuntimeReportTemporalProvenanceTracer": ".runtime_report_temporal_provenance",
    "KernelRuntimeReportFamilySummaryError": ".runtime_report_family_summary",
    "KernelRuntimeReportFamilySummarizer": ".runtime_report_family_summary",
    "RuntimeReportFamilyGenerationSpan": ".runtime_report_family_summary",
    "RuntimeReportFamilyLayerSummary": ".runtime_report_family_summary",
    "RuntimeReportFamilySummary": ".runtime_report_family_summary",
    "RuntimeReportFamilySummaryWriteResult": ".runtime_report_family_summary",
    "IonRuntimeReportFamilySummarizer": ".runtime_report_family_summary",
    "KernelRuntimeReportOperatorDigestError": ".runtime_report_operator_digest",
    "KernelRuntimeReportDigestProfileError": ".runtime_report_digest_profiles",
    "KernelRuntimeReportDigestProfiler": ".runtime_report_digest_profiles",
    "RuntimeReportDigestProfileSelector": ".runtime_report_digest_profiles",
    "RuntimeReportOperatorDigestProfile": ".runtime_report_digest_profiles",
    "RuntimeReportDigestProfileWriteResult": ".runtime_report_digest_profiles",
    "RuntimeReportDigestProfileDigestWriteResult": ".runtime_report_digest_profiles",
    "KernelRuntimeReportDigestProfileCatalogError": ".runtime_report_digest_profile_catalog",
    "KernelRuntimeReportDigestProfileCatalog": ".runtime_report_digest_profile_catalog",
    "RuntimeReportDigestProfileCatalogQuery": ".runtime_report_digest_profile_catalog",
    "RuntimeReportDigestProfileCatalogEntry": ".runtime_report_digest_profile_catalog",
    "RuntimeReportDigestProfileCatalog": ".runtime_report_digest_profile_catalog",
    "RuntimeReportDigestProfileCatalogWriteResult": ".runtime_report_digest_profile_catalog",
    "IonRuntimeReportDigestProfileCatalog": ".runtime_report_digest_profile_catalog",
    "KernelRuntimeReportDigestProfileBrowserError": ".runtime_report_digest_profile_browser",
    "KernelRuntimeReportDigestProfileBrowser": ".runtime_report_digest_profile_browser",
    "RuntimeReportDigestProfileBrowserSelectorView": ".runtime_report_digest_profile_browser",
    "RuntimeReportDigestProfileBrowserEntry": ".runtime_report_digest_profile_browser",
    "RuntimeReportDigestProfileBrowserFacetCounts": ".runtime_report_digest_profile_browser",
    "RuntimeReportDigestProfileBrowserResult": ".runtime_report_digest_profile_browser",
    "RuntimeReportDigestProfileBrowserWriteResult": ".runtime_report_digest_profile_browser",
    "IonRuntimeReportDigestProfileBrowser": ".runtime_report_digest_profile_browser",
    "KernelRuntimeReportProfileDigestTraceError": ".runtime_report_profile_digest_trace",
    "KernelRuntimeReportProfileDigestTracer": ".runtime_report_profile_digest_trace",
    "RuntimeReportProfileDigestTraceSelector": ".runtime_report_profile_digest_trace",
    "RuntimeReportProfileDigestTraceSelectorView": ".runtime_report_profile_digest_trace",
    "RuntimeReportProfileDigestTraceBrowserSelection": ".runtime_report_profile_digest_trace",
    "RuntimeReportProfileDigestTrace": ".runtime_report_profile_digest_trace",
    "RuntimeReportProfileDigestTraceWriteResult": ".runtime_report_profile_digest_trace",
    "IonRuntimeReportProfileDigestTracer": ".runtime_report_profile_digest_trace",
    "KernelRuntimeReportDigestReverseTraceError": ".runtime_report_digest_reverse_trace",
    "KernelRuntimeReportDigestReverseTracer": ".runtime_report_digest_reverse_trace",
    "RuntimeReportDigestReverseTraceSelector": ".runtime_report_digest_reverse_trace",
    "RuntimeReportDigestReverseTraceSelectorView": ".runtime_report_digest_reverse_trace",
    "RuntimeReportDigestReverseTraceQueryView": ".runtime_report_digest_reverse_trace",
    "RuntimeReportDigestReverseTraceCatalogSurface": ".runtime_report_digest_reverse_trace",
    "RuntimeReportDigestReverseTraceBrowserSurface": ".runtime_report_digest_reverse_trace",
    "RuntimeReportDigestReverseTraceForwardLink": ".runtime_report_digest_reverse_trace",
    "RuntimeReportDigestReverseTrace": ".runtime_report_digest_reverse_trace",
    "RuntimeReportDigestReverseTraceWriteResult": ".runtime_report_digest_reverse_trace",
    "IonRuntimeReportDigestReverseTracer": ".runtime_report_digest_reverse_trace",
    "KernelRuntimeReportBidirectionalTraceError": ".runtime_report_bidirectional_trace",
    "KernelRuntimeReportBidirectionalTracer": ".runtime_report_bidirectional_trace",
    "RuntimeReportBidirectionalTraceSelector": ".runtime_report_bidirectional_trace",
    "RuntimeReportBidirectionalForwardView": ".runtime_report_bidirectional_trace",
    "RuntimeReportBidirectionalReverseView": ".runtime_report_bidirectional_trace",
    "RuntimeReportBidirectionalTrace": ".runtime_report_bidirectional_trace",
    "RuntimeReportBidirectionalTraceWriteResult": ".runtime_report_bidirectional_trace",
    "IonRuntimeReportBidirectionalTracer": ".runtime_report_bidirectional_trace",
    "KernelRuntimeReportBidirectionalTraceComparisonError": ".runtime_report_bidirectional_trace_comparison",
    "KernelRuntimeReportBidirectionalTraceComparer": ".runtime_report_bidirectional_trace_comparison",
    "RuntimeReportBidirectionalTraceComparisonInput": ".runtime_report_bidirectional_trace_comparison",
    "RuntimeReportBidirectionalTraceComparisonEntry": ".runtime_report_bidirectional_trace_comparison",
    "RuntimeReportBidirectionalTraceComparisonSummary": ".runtime_report_bidirectional_trace_comparison",
    "RuntimeReportBidirectionalTraceComparison": ".runtime_report_bidirectional_trace_comparison",
    "RuntimeReportBidirectionalTraceComparisonWriteResult": ".runtime_report_bidirectional_trace_comparison",
    "IonRuntimeReportBidirectionalTraceComparer": ".runtime_report_bidirectional_trace_comparison",
    "KernelRuntimeReportBidirectionalTemporalError": ".runtime_report_bidirectional_trace_temporal",
    "KernelRuntimeReportBidirectionalTemporalTracer": ".runtime_report_bidirectional_trace_temporal",
    "RuntimeReportBidirectionalTemporalSelector": ".runtime_report_bidirectional_trace_temporal",
    "RuntimeReportBidirectionalTemporalGeneration": ".runtime_report_bidirectional_trace_temporal",
    "RuntimeReportBidirectionalTemporalAspectGeneration": ".runtime_report_bidirectional_trace_temporal",
    "RuntimeReportBidirectionalTemporalAspectTransition": ".runtime_report_bidirectional_trace_temporal",
    "RuntimeReportBidirectionalTemporalAspect": ".runtime_report_bidirectional_trace_temporal",
    "RuntimeReportBidirectionalTemporalTrace": ".runtime_report_bidirectional_trace_temporal",
    "RuntimeReportBidirectionalTemporalWriteResult": ".runtime_report_bidirectional_trace_temporal",
    "IonRuntimeReportBidirectionalTemporalTracer": ".runtime_report_bidirectional_trace_temporal",
    "KernelRuntimeReportBidirectionalFamilySummaryError": ".runtime_report_bidirectional_trace_family_summary",
    "KernelRuntimeReportBidirectionalFamilySummarizer": ".runtime_report_bidirectional_trace_family_summary",
    "RuntimeReportBidirectionalFamilyGenerationSpan": ".runtime_report_bidirectional_trace_family_summary",
    "RuntimeReportBidirectionalFamilyAspectSummary": ".runtime_report_bidirectional_trace_family_summary",
    "RuntimeReportBidirectionalFamilySummary": ".runtime_report_bidirectional_trace_family_summary",
    "RuntimeReportBidirectionalFamilySummaryWriteResult": ".runtime_report_bidirectional_trace_family_summary",
    "IonRuntimeReportBidirectionalFamilySummarizer": ".runtime_report_bidirectional_trace_family_summary",
    "IonRuntimeReportDigestProfiler": ".runtime_report_digest_profiles",
    "KernelRuntimeReportOperatorDigester": ".runtime_report_operator_digest",
    "RuntimeReportOperatorDigestFamilyEntry": ".runtime_report_operator_digest",
    "RuntimeReportOperatorDigestLayerOverview": ".runtime_report_operator_digest",
    "RuntimeReportOperatorDigest": ".runtime_report_operator_digest",
    "RuntimeReportOperatorDigestWriteResult": ".runtime_report_operator_digest",
    "IonRuntimeReportOperatorDigester": ".runtime_report_operator_digest",

    "KernelTemplateCompletionWatcher": ".template_completion_events",
    "IonTemplateCompletionWatcher": ".template_completion_events",
    "KernelTemplateCompletionEventError": ".template_completion_events",
    "IonTemplateCompletionEventError": ".template_completion_events",
    "TemplateCompletionWatchRule": ".template_completion_events",
    "TemplateCompletionCandidate": ".template_completion_events",
    "TemplateCompletionEventWitness": ".template_completion_events",
    "TemplateCompletionScanReceipt": ".template_completion_events",
    "KernelTemplateReactionSelector": ".template_reaction_selection",
    "IonTemplateReactionSelector": ".template_reaction_selection",
    "KernelTemplateReactionSelectionError": ".template_reaction_selection",
    "IonTemplateReactionSelectionError": ".template_reaction_selection",
    "GraphReactionFamily": ".template_reaction_selection",
    "TemplateReactionSelection": ".template_reaction_selection",
    "TemplateReactionSelectionWitness": ".template_reaction_selection",
    "TemplateReactionSelectionScanReceipt": ".template_reaction_selection",
    "KernelTemplateIndexProjector": ".template_index_projection",
    "IonTemplateIndexProjector": ".template_index_projection",
    "KernelTemplateIndexProjectionError": ".template_index_projection",
    "IonTemplateIndexProjectionError": ".template_index_projection",
    "TemplateIndexProjectionEntry": ".template_index_projection",
    "TemplateIndexProjectionDeferral": ".template_index_projection",
    "TemplateIndexProjectionSurface": ".template_index_projection",
    "TemplateIndexProjectionReceipt": ".template_index_projection",
    "KernelTemplateGraphWritebackProposer": ".template_graph_writeback_proposals",
    "IonTemplateGraphWritebackProposer": ".template_graph_writeback_proposals",
    "KernelTemplateGraphWritebackProposalError": ".template_graph_writeback_proposals",
    "IonTemplateGraphWritebackProposalError": ".template_graph_writeback_proposals",
    "ProposedTemplateGraphNode": ".template_graph_writeback_proposals",
    "ProposedTemplateGraphEdge": ".template_graph_writeback_proposals",
    "DeferredTemplateGraphReaction": ".template_graph_writeback_proposals",
    "TemplateGraphWritebackProposal": ".template_graph_writeback_proposals",
    "TemplateGraphWritebackProposalReceipt": ".template_graph_writeback_proposals",
}

__all__ = [
    "AgentIdentity",
    "ArtifactOperation",
    "AuthorityClass",
    "ChildAgentBinding",
    "ChildSpec",
    "ChildWorkIssuancePreparation",
    "ChildWorkIssuanceResult",
    "CommitDelta",
    "PlannerIntentType",
    "PlannerManifest",
    "PlannerManifestStatus",
    "PlannerManifestSweepReceipt",
    "PlannerManifestSweepAggregateRecord",
    "QuestionAnswerRecord",
    "ReviewerAnswerQueueProjectionRecord",
    "ReviewerQueueRefreshReceipt",
    "CommitDeltaStatus",
    "CanonicalSignalType",
    "CommitApplication",
    "CommitApplicationResult",
    "DaemonActionCandidate",
    "DaemonActionType",
    "DaemonArbitrationResult",
    "DaemonActOnceResult",
    "DaemonActOnceStatus",
    "DaemonLoopResult",
    "DaemonLoopStatus",
    "ContextCompileRequest",
    "ContextCompilerError",
    "ContextPackage",
    "ContextTiers",
    "DependencyInterface",
    "DispatchPacket",
    "DispatchPreparation",
    "DispatchResult",
    "ExecutionPreparation",
    "ExecutionResult",
    "ExecutionSubmission",
    "ExecutionBundle",
    "GraphEdge",
    "GraphEdgeType",
    "default_repo_root",
    "InputRef",
    "InputRefType",
    "InputVisibility",
    "IonDaemonActuator",
    "IonDaemonLoop",
    "IonChildWorkIssuer",
    "IonDaemonArbiter",
    "IonGraph",
    "IonDispatcher",
    "IonExecutor",
    "IonCommitApplier",
    "IonQuestionRouter",
    "IonQuestionAnswerIngestor",
    "IonQuestionAnswerProjectionBuilder",
    "IonPlannerChildIssuanceGate",
    "IonReceiptEmitter",
    "IonReviewEscalator",
    "IonSignalConsumer",
    "IonSignalFollowUpHandler",
    "IonSignalInterpreter",
    "IonValidator",
    "IonIndex",
    "IonScheduler",
    "IonStore",
    "KernelExecutionError",
    "KernelCommitApplier",
    "KernelCommitError",
    "KernelChildWorkIssuer",
    "KernelChildWorkIssuanceError",
    "KernelDaemonActionError",
    "KernelDaemonActuator",
    "KernelDaemonArbiter",
    "KernelDaemonLoop",
    "KernelDaemonLoopError",
    "KernelQuestionRouter",
    "KernelQuestionAnswerError",
    "KernelQuestionAnswerIngestor",
    "KernelQuestionAnswerProjectionBuilder",
    "KernelPlannerChildIssuanceGate",
    "KernelPlannerGateError",
    "KernelQuestionRoutingError",
    "KernelReceiptEmitter",
    "KernelReceiptError",
    "KernelReviewEscalationError",
    "KernelReviewEscalator",
    "KernelSignalConsumer",
    "KernelSignalConsumerError",
    "KernelSignalFollowUpError",
    "KernelSignalFollowUpHandler",
    "KernelSignalInterpreter",
    "KernelDispatchError",
    "KernelRecord",
    "KernelGraph",
    "KernelIndex",
    "KernelExecutor",
    "KernelDispatcher",
    "KernelValidationError",
    "KernelValidator",
    "KernelScheduler",
    "KernelSchedulerError",
    "KernelStore",
    "KernelStoreError",
    "LedgerEntry",
    "LoadTarget",
    "OpenQuestion",
    "OpenQuestionPriority",
    "OpenQuestionStatus",
    "ParsedQuestionDirective",
    "PriorFinding",
    "PreparedChildWork",
    "ProducedArtifact",
    "ProposedSignal",
    "ReceiptEmissionResult",
    "ReceiptPreparation",
    "SignalLifecycleStatus",
    "SignalConsumptionResult",
    "SignalExpirationResult",
    "SignalFileRef",
    "SignalFollowUpDisposition",
    "SignalFollowUpPreparation",
    "SignalFollowUpResult",
    "SignalInterpretation",
    "SignalInterpretationResult",
    "SignalMeaning",
    "SignalRecommendedAction",
    "SIGNAL_FOLLOWUP_DOMAIN",
    "QuestionResolutionResult",
    "QuestionAnswerSubmission",
    "QuestionAnswerProjection",
    "ReviewerAnswerQueue",
    "ReviewerAnswerQueueProjectionResult",
    "QuestionAnswerPreparation",
    "QuestionAnswerResult",
    "ReviewerQueueRefreshCandidate",
    "ReviewerQueueRefreshResult",
    "reviewer_queue_projection_id",
    "planner_manifest_id",
    "PlannerManifestPreparation",
    "PlannerManifestCompileCandidate",
    "PlannerManifestMaintenanceCandidate",
    "PlannerManifestResult",
    "PlannerManifestSweepResult",
    "PlannerManifestSweepAggregateResult",
    "planner_manifest_sweep_receipt_id",
    "planner_manifest_sweep_aggregate_id",
    "PlannerChildIssuancePreparation",
    "PlannerChildIssuanceResult",
    "QuestionRoutingPreparation",
    "QuestionRoutingResult",
    "REVIEW_DOMAIN",
    "ReviewEscalationPreparation",
    "ReviewEscalationResult",
    "RoleConfig",
    "RolePass",
    "RoleSession",
    "ScheduleReason",
    "ScopeType",
    "SequentialKernelRouter",
    "SequentialTrace",
    "SemanticOverlay",
    "SpawnPolicy",
    "StateMutation",
    "StateMutationOperation",
    "StrEnum",
    "TaskRetirement",
    "TargetFile",
    "TierFiveDependencies",
    "TierFourSemantic",
    "TierOneDoctrine",
    "TierThreeMission",
    "TierTwoTarget",
    "AutomationGate",
    "AutomationStage",
    "AutomationStatePreparation",
    "AutomationStateRecord",
    "AutomationStateResult",
    "CalibrationStatus",
    "CapsuleDriftCheckResult",
    "EvidencePressure",
    "CapsuleRecord",
    "ContextMode",
    "GovernedWriteReceipt",
    "GovernedWriteRequest",
    "GovernedWriteStageResult",
    "IonAutomationStateManager",
    "IonCapsuleManager",
    "IonManifestRouteStateManager",
    "IonGovernedWriter",
    "IonThresholdEvaluator",
    "KernelAutomationStateError",
    "KernelAutomationStateManager",
    "KernelCapsuleError",
    "KernelCapsuleManager",
    "KernelGovernedWriteError",
    "KernelManifestRouteStateError",
    "KernelManifestRouteStateManager",
    "KernelGovernedWriter",
    "KernelThresholdError",
    "KernelThresholdEvaluator",
    "KernelRuntimeStateSync",
    "RuntimeStateSyncResult",
    "IonRuntimeStateSync",
    "KernelRuntimeStateView",
    "RuntimeStateScopeView",
    "RuntimeReviewPressure",
    "RuntimeDispatchPosture",
    "IonRuntimeStateView",
    "KernelRuntimeReportArtifactError",
    "KernelRuntimeReportArtifactEmitter",
    "RuntimeReportArtifactKind",
    "RuntimeReportArtifact",
    "RuntimeReportArtifactPreparation",
    "RuntimeReportArtifactResult",
    "IonRuntimeReportArtifactEmitter",
    "KernelRuntimeReportingError",
    "KernelRuntimeStateReporter",
    "RuntimeScopeStatusBundle",
    "IonRuntimeStateReporter",
    "KernelRuntimeReportTriggerError",
    "KernelRuntimeReportTriggerManager",
    "RuntimeReportTriggerEvent",
    "RuntimeReportTriggerRequest",
    "RuntimeReportTriggerReceipt",
    "IonRuntimeReportTriggerManager",
    "KernelRuntimeReportGovernanceError",
    "KernelRuntimeReportGovernanceManager",
    "RuntimeReportGovernanceBatchResult",
    "IonRuntimeReportGovernanceManager",
    "KernelRuntimeReportGovernanceAggregationError",
    "KernelRuntimeReportGovernanceAggregationManager",
    "RuntimeReportGovernanceAggregationBatchResult",
    "IonRuntimeReportGovernanceAggregationManager",
    "ManifestModeBinding",
    "ManifestRouteStatePreparation",
    "ManifestRouteStateRecord",
    "ManifestRouteStateResult",
    "PromotionAction",
    "RouteBranch",
    "RouteFrame",
    "RouteOwnerScope",
    "RouteStage",
    "RoutingAssessment",
    "ThresholdCondition",
    "ThresholdEvaluation",
    "ThresholdHit",
    "ThresholdOperator",
    "ThresholdSnapshot",
    "ValidationDecision",
    "ValidationReceipt",
    "WorkPriority",
    "WorkUnitDispatchAssessment",
    "WorkUnit",
    "WorkUnitStatus",
    "Workstream",
    "automation_state_record_id",
    "compile_context_package",
    "compile_context_package_for_work_unit",
    "find_session_path",
    "record_bundle_session_update",
    "record_session_update",
    "render_dispatch_packet",
    "manifest_route_state_id",
    "render_context_package_text",
    "retire_task_packet",
    "write_dispatch_packet",
    "write_execution_bundle",
    "write_trace_artifact",
    "EmittedSignal",
    "KernelRuntimeReportBrowserError",
    "KernelRuntimeReportBrowser",
    "RuntimeReportBrowserFacetCounts",
    "RuntimeReportBrowserResult",
    "RuntimeReportBrowserWriteResult",
    "IonRuntimeReportBrowser",
    "KernelRuntimeReportCrosslinkError",
    "KernelRuntimeReportCrosslinker",
    "RuntimeReportCrosslinkTarget",
    "RuntimeReportCrosslinkedEntry",
    "RuntimeReportCrosslinkView",
    "RuntimeReportCrosslinkWriteResult",
    "IonRuntimeReportCrosslinker",
    "KernelRuntimeReportProvenanceError",
    "KernelRuntimeReportProvenanceTracer",
    "RuntimeReportProvenanceSelector",
    "RuntimeReportProvenanceTarget",
    "RuntimeReportProvenanceLayer",
    "RuntimeReportProvenanceTrace",
    "RuntimeReportProvenanceWriteResult",
    "IonRuntimeReportProvenanceTracer",
    "KernelRuntimeReportComparativeProvenanceError",
    "KernelRuntimeReportComparativeProvenanceTracer",
    "RuntimeReportComparativeSelector",
    "RuntimeReportComparativeReceipt",
    "RuntimeReportComparativeLayerReceipt",
    "RuntimeReportComparativeLayer",
    "RuntimeReportComparativeTrace",
    "RuntimeReportComparativeWriteResult",
    "IonRuntimeReportComparativeProvenanceTracer",
    "KernelRuntimeReportTemporalProvenanceError",
    "KernelRuntimeReportTemporalProvenanceTracer",
    "RuntimeReportTemporalSelector",
    "RuntimeReportTemporalGeneration",
    "RuntimeReportTemporalLayerGeneration",
    "RuntimeReportTemporalLayerTransition",
    "RuntimeReportTemporalLayer",
    "RuntimeReportTemporalTrace",
    "RuntimeReportTemporalWriteResult",
    "IonRuntimeReportTemporalProvenanceTracer",
    "KernelRuntimeReportFamilySummaryError",
    "KernelRuntimeReportFamilySummarizer",
    "RuntimeReportFamilyGenerationSpan",
    "RuntimeReportFamilyLayerSummary",
    "RuntimeReportFamilySummary",
    "RuntimeReportFamilySummaryWriteResult",
    "IonRuntimeReportFamilySummarizer",
    "KernelRuntimeReportDigestProfileBrowserError",
    "KernelRuntimeReportDigestProfileBrowser",
    "RuntimeReportDigestProfileBrowserSelectorView",
    "RuntimeReportDigestProfileBrowserEntry",
    "RuntimeReportDigestProfileBrowserFacetCounts",
    "RuntimeReportDigestProfileBrowserResult",
    "RuntimeReportDigestProfileBrowserWriteResult",
    "IonRuntimeReportDigestProfileBrowser",
    "KernelRuntimeReportBidirectionalTraceError",
    "KernelRuntimeReportBidirectionalTracer",
    "RuntimeReportBidirectionalTraceSelector",
    "RuntimeReportBidirectionalForwardView",
    "RuntimeReportBidirectionalReverseView",
    "RuntimeReportBidirectionalTrace",
    "RuntimeReportBidirectionalTraceWriteResult",
    "IonRuntimeReportBidirectionalTracer",
    "KernelRuntimeReportBidirectionalTraceComparisonError",
    "KernelRuntimeReportBidirectionalTraceComparer",
    "RuntimeReportBidirectionalTraceComparisonInput",
    "RuntimeReportBidirectionalTraceComparisonEntry",
    "RuntimeReportBidirectionalTraceComparisonSummary",
    "RuntimeReportBidirectionalTraceComparison",
    "RuntimeReportBidirectionalTraceComparisonWriteResult",
    "IonRuntimeReportBidirectionalTraceComparer",

    "KernelTemplateCompletionWatcher",
    "IonTemplateCompletionWatcher",
    "KernelTemplateCompletionEventError",
    "IonTemplateCompletionEventError",
    "TemplateCompletionWatchRule",
    "TemplateCompletionCandidate",
    "TemplateCompletionEventWitness",
    "TemplateCompletionScanReceipt",
    "KernelTemplateReactionSelector",
    "IonTemplateReactionSelector",
    "KernelTemplateReactionSelectionError",
    "IonTemplateReactionSelectionError",
    "GraphReactionFamily",
    "TemplateReactionSelection",
    "TemplateReactionSelectionWitness",
    "TemplateReactionSelectionScanReceipt",
    "KernelTemplateIndexProjector",
    "IonTemplateIndexProjector",
    "KernelTemplateIndexProjectionError",
    "IonTemplateIndexProjectionError",
    "TemplateIndexProjectionEntry",
    "TemplateIndexProjectionDeferral",
    "TemplateIndexProjectionSurface",
    "TemplateIndexProjectionReceipt",
    "FrontDoorSelfMountBinding",
    "FrontDoorSelfMountBindingReceipt",
    "FrontDoorSelfMountBindingResult",
    "bind_front_door_self_mount",
    "validate_front_door_self_mount_binding",
    "write_front_door_self_mount_binding",
    "write_front_door_self_mount_binding_receipt",
    "format_front_door_self_mount_binding_summary",
    "SelfSurfaceDriftSignal",
    "SelfSurfaceDriftAssessment",
    "assess_self_surface_text",
    "validate_self_surface_drift_assessment",
    "write_self_surface_drift_assessment",
    "AgentSuccessionPacket",
    "AgentSuccessionPacketReceipt",
    "generate_agent_succession_packet",
    "validate_agent_succession_packet",
    "write_agent_succession_packet",
    "SelfMountGraphNode",
    "SelfMountGraphEdge",
    "SelfMountGraphProjection",
    "generate_self_mount_graph_projection",
    "validate_self_mount_graph_projection",
    "write_self_mount_graph_projection",
]


def __getattr__(name: str) -> Any:
    if name in _EXPORT_MODULES:
        module = import_module(_EXPORT_MODULES[name], __name__)
        return getattr(module, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
