"""Deterministic ION carrier-cycle planner.

This module closes the gap exposed by Cursor carrier operation: the carrier must
not decide whether to run kernel-only, all roles, or arbitrary Tasks from chat.
It must ask ION for the cycle plan, then execute only the generated role-session
packets.

The module does not call Cursor's Task API. It emits a carrier-executable spawn
plan and an execution bundle generated by the existing SequentialKernelRouter.
Cursor or any other carrier must treat that plan as authority.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Mapping

from .sequential_kernel import LoadTarget, SequentialKernelRouter, Workstream, default_repo_root, write_execution_bundle
from .ion_agent_context_systems import agent_context_system_paths, runtime_context_system_summary

ACTIVE_SPAWN_PLAN_RELATIVE_PATH = Path("ION/05_context/current/ACTIVE_ROLE_SPAWN_PLAN.json")
DEFAULT_EXECUTION_ROOT = Path("ION/05_context/current/execution_cycles")

ROLE_AUTHORITY_DEFAULTS: dict[str, str] = {
    "steward": "ORCHESTRATION_AND_INTEGRATION_BOUNDED",
    "vizier": "SCOPE_AND_DEPENDENCY_REVIEW_BOUNDED",
    "mason": "IMPLEMENTATION_BOUNDED_TO_PACKET_ALLOWED_PATHS",
    "codex": "IMPLEMENTATION_BOUNDED_TO_PACKET_ALLOWED_PATHS",
    "scribe": "DOCUMENTATION_BOUNDED_TO_PACKET_ALLOWED_PATHS",
    "relay": "VISIBLE_REPORT_BOUNDED",
    "vice": "RISK_PRESSURE_AND_GOVERNANCE_REVIEW_BOUNDED",
    "nemesis": "AUDIT_AND_RELEASE_SENSITIVITY_REVIEW_BOUNDED",
    "auditor": "VALIDATION_BOUNDED",
    "vestige": "PROVENANCE_AND_RECOVERY_REVIEW_BOUNDED",
}


def _iso_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def _resolve_shell_root(root: str | Path | None) -> Path:
    if root is None:
        return default_repo_root()
    candidate = Path(root).expanduser().resolve()
    if (candidate / "ION" / "04_packages" / "kernel").is_dir():
        return candidate
    if candidate.name == "ION" and (candidate / "04_packages" / "kernel").is_dir():
        return candidate.parent
    return default_repo_root(candidate)


def _slug(value: str) -> str:
    import re
    return re.sub(r"[^a-z0-9]+", "_", value.lower()).strip("_")[:80] or "cycle"


def _should_spawn_optional(role: str, objective: str, policy: str) -> bool:
    if policy == "full":
        return True
    if policy == "required":
        return False
    text = objective.lower()
    if role in {"vice", "nemesis"}:
        return any(word in text for word in ("risk", "governance", "release", "authority", "audit", "safety", "continuity", "critical", "incident"))
    return False


def _authority_for_role(role: str, packet_authority: Mapping[str, Any] | None = None) -> str:
    packet_authority = dict(packet_authority or {})
    if role in packet_authority:
        return str(packet_authority[role])
    return ROLE_AUTHORITY_DEFAULTS.get(role, "PACKET_BOUNDED_ROLE_AUTHORITY")


_MAX_CONTEXT_INLINE_CHARS = 24000
_MAX_CONTEXT_TOTAL_CHARS = 90000


def _safe_relative(path: Path, root: Path) -> str:
    try:
        return str(path.relative_to(root))
    except ValueError:
        return str(path)


def _sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def _first_meaningful_line(text: str) -> str:
    for line in text.splitlines():
        stripped = line.strip()
        if stripped:
            return stripped[:240]
    return ""


def _read_text_lossy(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def _target_receipt(shell_root: Path, target: Any) -> dict[str, Any]:
    """Return a deterministic read receipt for one sequential-kernel load target."""

    rel = str(target.path)
    receipt: dict[str, Any] = {
        "label": str(target.label),
        "path": rel,
        "kind": str(target.kind),
        "required": bool(target.required),
        "note": str(target.note or ""),
        "exists": False,
        "status": "missing",
    }

    if target.kind == "glob":
        matches = sorted(_safe_relative(path, shell_root) for path in shell_root.glob(rel))
        receipt.update({
            "exists": bool(matches),
            "status": "matched" if matches else "missing_optional_glob" if not target.required else "missing_required_glob",
            "matches": matches[:50],
            "match_count": len(matches),
        })
        return receipt

    path = shell_root / rel
    receipt["exists"] = path.exists()
    if not path.exists():
        receipt["status"] = "missing_required" if target.required else "missing_optional"
        return receipt

    if path.is_dir():
        entries = sorted(child.name for child in path.iterdir())[:50]
        receipt.update({
            "status": "directory_present",
            "entry_count_sampled": len(entries),
            "entries_sample": entries,
        })
        return receipt

    if path.is_file():
        text = _read_text_lossy(path)
        receipt.update({
            "status": "file_present",
            "sha256": _sha256_file(path),
            "bytes": path.stat().st_size,
            "line_count": text.count("\n") + (0 if text.endswith("\n") or text == "" else 1),
            "first_meaningful_line": _first_meaningful_line(text),
        })
        return receipt

    receipt["status"] = "present_non_file_non_dir"
    return receipt


def _context_system_load_targets(shell_root: Path, role: str) -> tuple[LoadTarget, ...]:
    """Return ordered V82 context-system surfaces for a role."""

    targets: list[LoadTarget] = []
    for index, rel_path in enumerate(agent_context_system_paths(shell_root, role), start=1):
        targets.append(
            LoadTarget(
                label=f"{role}.context_system.{index}",
                path=rel_path,
                required=rel_path.endswith(".context_system.md") or rel_path.endswith("ION_AGENT_CONTEXT_SYSTEMS_PROTOCOL.md") or rel_path.endswith("agent_context_system_registry.yaml"),
                note="V82 Agent Context System surface; governs legacy MINI/CAPSULE interpretation",
            )
        )
    return tuple(targets)


def _dedupe_load_targets(targets: list[LoadTarget]) -> tuple[LoadTarget, ...]:
    seen: set[tuple[str, str]] = set()
    ordered: list[LoadTarget] = []
    for target in targets:
        key = (str(target.kind), str(target.path))
        if key in seen:
            continue
        seen.add(key)
        ordered.append(target)
    return tuple(ordered)


def _inline_file_block(shell_root: Path, receipt: Mapping[str, Any], remaining_budget: int) -> tuple[str, int]:
    """Render a parent-prefetched context block, preserving a strict budget."""

    if receipt.get("status") != "file_present" or remaining_budget <= 0:
        return "", remaining_budget
    rel = str(receipt["path"])
    path = shell_root / rel
    text = _read_text_lossy(path)
    inline_limit = min(_MAX_CONTEXT_INLINE_CHARS, remaining_budget)
    truncated = len(text) > inline_limit
    body = text[:inline_limit]
    remaining_budget -= len(body)
    fence = "```"
    block = [
        f"### {rel}",
        "",
        f"- sha256: `{receipt.get('sha256', '')}`",
        f"- line_count: `{receipt.get('line_count', '')}`",
        f"- inline_status: {'TRUNCATED_PARENT_PREFETCH' if truncated else 'FULL_PARENT_PREFETCH'}",
        "",
        fence + "text",
        body.rstrip(),
        fence,
        "",
    ]
    if truncated:
        block.append(
            "Parent prefetch was truncated. The Task worker must still use the file-read tool on this path and prove EOF/line coverage in `### CONTEXT PROOF`.\n"
        )
    return "\n".join(block), remaining_budget


def materialize_cursor_task_context_package(
    *,
    shell_root: Path,
    run_root: Path,
    index: int,
    role: str,
    workstream: str,
    objective: str,
    session_path: Path,
    session: Any,
    authority: str,
    spawn: bool,
) -> dict[str, Any]:
    """Write a Cursor Task prompt + receipt that converts required reads into a proof transaction.

    The crucial distinction is that this artifact is not merely a pointer to a boot file.
    It is a carrier-readable ContextPackage that tells the Task worker to perform
    ordered file reads, prove those reads, and only then execute the bounded role pass.
    """

    role_upper = role.upper()
    rel_session = _safe_relative(session_path, shell_root)
    context_system_summary = runtime_context_system_summary(shell_root, role)
    active_load_targets = _dedupe_load_targets([*_context_system_load_targets(shell_root, role), *session.load_targets])
    receipts = [_target_receipt(shell_root, target) for target in active_load_targets]
    context_system_read_paths = [
        r["path"]
        for r in receipts
        if str(r.get("label", "")).startswith(f"{role}.context_system") and r.get("kind") == "file" and r.get("exists")
    ]
    read_paths = [r["path"] for r in receipts if r.get("kind") == "file" and r.get("exists")]
    required_missing = [r["path"] for r in receipts if r.get("required") and not r.get("exists")]

    receipt_path = run_root / f"{index:02d}_{role}_context_load_receipt.json"
    prompt_path = run_root / f"{index:02d}_{role}_cursor_task_prompt.md"
    compiled_bundle_path = run_root / f"{index:02d}_COMPILED_{role_upper}_CONTEXT_BUNDLE.md"

    remaining = _MAX_CONTEXT_TOTAL_CHARS
    inline_blocks: list[str] = []
    for receipt in receipts:
        block, remaining = _inline_file_block(shell_root, receipt, remaining)
        if block:
            inline_blocks.append(block)

    read_steps = []
    for n, receipt in enumerate(receipts, start=1):
        status = receipt.get("status")
        sha = receipt.get("sha256")
        suffix = f" sha256={sha}" if sha else f" status={status}"
        read_steps.append(f"{n}. `{receipt['path']}` ({receipt['kind']}; required={str(receipt['required']).lower()};{suffix})")

    prompt_lines = [
        f"# ION Cursor Task ContextPackage — {role_upper}",
        "",
        "This prompt is the executable ContextPackage for a Cursor Task carrier slot. It is not a generic instruction to 'read a file'. The worker must complete the context-load transaction, prove it, then execute the bounded role pass.",
        "",
        "## Mount",
        "",
        f"- agent_name: `{role_upper}`",
        "- carrier: `cursor_subagent`",
        "- mounted_by: `local_STEWARD_carrier`",
        f"- authority_level: `{authority}`",
        "- production_authority: `false`",
        "- live_execution_authority: `false`",
        f"- workstream: `{workstream}`",
        f"- session_packet_path: `{rel_session}`",
        "- proposal_status: `PENDING_STEWARD_REVIEW`",
        "",
        "## Mission",
        "",
        objective,
        "",
        "## Agent Context System authority",
        "",
        "This Task package is V82 Agent-Context-System aware. The role is not being booted from MINI/CAPSULE as primary authority; those files are continuity witnesses interpreted under the active package.",
        "",
        f"- context_system_status: `{context_system_summary.get('status')}`",
        f"- context_system_card: `{context_system_summary.get('context_system_card')}`",
        f"- active_package_class: `{context_system_summary.get('default_active_package_class')}`",
        f"- package_strategy: {context_system_summary.get('package_strategy') or 'not declared'}",
        f"- package_policy: {context_system_summary.get('policy')}",
        "",
        "The Agent Context System card and package-build templates must be read before legacy private MINI/CAPSULE surfaces are treated as evidence. If they conflict, the active context package and current registry outrank legacy witness surfaces.",
        "",
        "## Required context-load transaction",
        "",
        "Before analysis or edits, use Cursor's file-read tool (`Read` / `read_file`) on each file path below in this exact sequence. Directory and glob rows must be checked/listed when relevant. Parent-prefetched content later in this prompt is only a checksum-backed aid; it does not replace tool-read proof.",
        "",
        *read_steps,
        "",
        "## Required first output section",
        "",
        "Your response must begin with exactly this heading:",
        "",
        "```markdown",
        "### CONTEXT PROOF",
        "```",
        "",
        "Under that heading, list every required read in order with: `path`, `status`, `line_count or EOF`, `sha256 if available`, and one short verbatim excerpt from the file you actually read. If a read fails, state the error and stop; do not fake context.",
        "",
        "## Execution rule",
        "",
        "After `### CONTEXT PROOF`, apply the loaded boot/session material as law. Do not merely report that you have context. Execute the bounded role pass and return only proposal/evidence for Steward integration.",
        "",
        "## Return contract",
        "",
        "- `### CONTEXT PROOF` as specified above",
        "- `### TEMPLATE ACTION PROOF` with `template_id`, `action_id`, `result`, and `touched_paths` for Steward integration",
        "- Approved `template_id` values: `ion.template.audit_observation.v1`, `ion.template.patch_proposal.v1`, `ion.template.context_system.maintenance.v1`, `ion.template.autonomous_loop.local_worker.v1`.",
        "- Use `ion.template.audit_observation.v1` for no-edit review/evidence returns. Do not use binding file paths such as `ION/07_templates/bindings/STEWARD__TASK.md` as `template_id`.",
        "- `touched_paths` must list at least one repo-relative evidence or changed path. For no-edit returns, list the active packet, receipt, or source paths inspected.",
        "- `### ROLE PASS` with the role's actual analysis or proposed changes",
        "- `### FILES INSPECTED` with paths and why each mattered",
        "- `### PROPOSED CHANGES` or `### NO CHANGE PROPOSED`",
        "- `### RISKS / BLOCKERS`",
        "- `### STEWARD INTEGRATION NOTES`",
        "",
        "## Return acceptance gate",
        "",
        "The parent carrier / Steward must reject the Task return unless it starts with `### CONTEXT PROOF`, passes `kernel.ion_context_proof_gate` against this prompt's `*_context_load_receipt.json`, and passes `kernel.ion_template_action_gate`. A recap such as `I read the context file` is not onboarded evidence.",
        "",
        "## Parent-prefetched context payload",
        "",
        "The following content was prefetched by the parent carrier and checksummed into the receipt. Use it to reduce model drift, but still perform the explicit file-read proof above.",
        "",
    ]
    prompt_lines.extend(inline_blocks or ["No file content was inlined; perform the required file reads from disk."])

    prompt_text = "\n".join(prompt_lines).rstrip() + "\n"
    prompt_path.write_text(prompt_text, encoding="utf-8")

    # V95 invariant: every spawned role gets a physical
    # COMPILED_<ROLE>_CONTEXT_BUNDLE.md file.  This is a law-complete alias of
    # the executable context package, added so Cursor cannot infer that only
    # Steward/Relay have compiled one-file context bundles.
    compiled_bundle_text = "\n".join([
        f"# COMPILED {role_upper} CONTEXT BUNDLE",
        "",
        "This V95 bundle is the same executable ION Task ContextPackage materialized under an explicit COMPILED_<ROLE>_CONTEXT_BUNDLE filename. Use it exactly as the generated context package; do not fall back to boot/MINI/CAPSULE/session-only onboarding.",
        "",
        f"- role: `{role_upper}`",
        f"- context_package_path: `{_safe_relative(prompt_path, shell_root)}`",
        f"- context_load_receipt_path: `{_safe_relative(receipt_path, shell_root)}`",
        "- output_must_begin_with: `### CONTEXT PROOF`",
        "- output_must_include: `### TEMPLATE ACTION PROOF`",
        "- legacy_private_state: `witness input only, never primary authority`",
        "",
        "---",
        "",
        prompt_text.rstrip(),
        "",
    ])
    compiled_bundle_path.write_text(compiled_bundle_text, encoding="utf-8")

    receipt_payload = {
        "schema_id": "ion.cursor_task_context_load_receipt.v1",
        "created_at": _iso_now(),
        "role": role,
        "agent_name": role_upper,
        "workstream": workstream,
        "objective": objective,
        "spawn": spawn,
        "authority": authority,
        "session_packet_path": rel_session,
        "task_prompt_path": _safe_relative(prompt_path, shell_root),
        "compiled_context_bundle_path": _safe_relative(compiled_bundle_path, shell_root),
        "compiled_context_bundle_sha256": _sha256_file(compiled_bundle_path),
        "agent_context_system": context_system_summary,
        "context_system_read_paths": context_system_read_paths,
        "required_context_reads": receipts,
        "read_paths_ordered": read_paths,
        "required_missing": required_missing,
        "context_load_contract": "TASK_OUTPUT_MUST_BEGIN_WITH_CONTEXT_PROOF_AND_INCLUDE_TEMPLATE_ACTION_PROOF",
        "context_proof_return_gate": "kernel.ion_context_proof_gate",
        "template_action_return_gate": "kernel.ion_template_action_gate",
        "template_action_allowed_template_ids": [
            "ion.template.audit_observation.v1",
            "ion.template.patch_proposal.v1",
            "ion.template.context_system.maintenance.v1",
            "ion.template.autonomous_loop.local_worker.v1",
        ],
        "parent_prefetch_budget_chars": _MAX_CONTEXT_TOTAL_CHARS,
        "production_authority": False,
        "live_execution_authority": False,
    }
    receipt_path.write_text(json.dumps(receipt_payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    return {
        "context_package_path": _safe_relative(prompt_path, shell_root),
        "compiled_context_bundle_path": _safe_relative(compiled_bundle_path, shell_root),
        "context_load_receipt_path": _safe_relative(receipt_path, shell_root),
        "context_load_contract": receipt_payload["context_load_contract"],
        "context_proof_return_gate": receipt_payload["context_proof_return_gate"],
        "template_action_return_gate": receipt_payload["template_action_return_gate"],
        "agent_context_system": context_system_summary,
        "context_system_read_paths": context_system_read_paths,
        "read_paths_ordered": read_paths,
        "required_missing": required_missing,
    }


def build_cycle_plan(
    root: str | Path | None,
    *,
    workstream: str,
    objective: str,
    carrier: str = "cursor",
    spawn_policy: str = "required",
    spawn_row_limit: int | None = None,
    execution_root: str | Path | None = None,
    source_task: str | None = None,
    packet_authority: Mapping[str, Any] | None = None,
    completed_role_indexes: set[int] | None = None,
    completed_role_evidence: Mapping[int, Mapping[str, Any]] | None = None,
) -> dict[str, Any]:
    """Build a deterministic role-spawn plan from the ION sequential kernel.

    spawn_policy:
      - required: spawn only required role passes.
      - full: spawn required and optional role passes.
      - objective: spawn required role passes and optional passes only when the
        objective makes them relevant.
    """

    if spawn_policy not in {"required", "full", "objective"}:
        raise ValueError("spawn_policy must be one of: required, full, objective")

    shell_root = _resolve_shell_root(root)
    completed_role_indexes = set(completed_role_indexes or set())
    completed_role_evidence = dict(completed_role_evidence or {})
    router = SequentialKernelRouter.default(shell_root)
    trace = router.build_trace(Workstream(workstream), objective=objective)
    missing = trace.missing_required(shell_root)

    if execution_root is None:
        execution_root = DEFAULT_EXECUTION_ROOT / f"{_iso_now().replace(':', '').replace('+', 'Z')}_{workstream}_{_slug(objective)}"
    execution_root_path = Path(execution_root)
    if not execution_root_path.is_absolute():
        execution_root_path = shell_root / execution_root_path
    materialize_execution_bundle = spawn_row_limit != 0
    bundle = (
        write_execution_bundle(trace, shell_root, execution_root_path, source_task=source_task)
        if materialize_execution_bundle
        else None
    )

    roles: list[dict[str, Any]] = []
    active_spawn_count = 0
    deferred_spawn_count = 0
    for index, (role_pass, session) in enumerate(zip(trace.passes, trace.sessions), start=1):
        role = role_pass.role_name
        optional = not role_pass.required
        spawn_intent = role_pass.required or _should_spawn_optional(role, objective, spawn_policy)
        already_integrated = index in completed_role_indexes
        deferred_by_limit = False
        spawn = spawn_intent and not already_integrated
        if spawn and spawn_row_limit is not None:
            limit = max(0, spawn_row_limit)
            if active_spawn_count >= limit:
                spawn = False
                deferred_by_limit = True
            else:
                active_spawn_count += 1
        elif spawn:
            active_spawn_count += 1

        if deferred_by_limit:
            deferred_spawn_count += 1

        session_path = bundle.session_paths[index - 1] if bundle is not None else None
        authority = _authority_for_role(role, packet_authority) if spawn else (
            "ALREADY_INTEGRATED"
            if already_integrated
            else "DEFERRED_BY_SPAWN_ROW_LIMIT" if deferred_by_limit else "NOT_SPAWNED"
        )
        context_package = (
            materialize_cursor_task_context_package(
                shell_root=shell_root,
                run_root=bundle.run_root,
                index=index,
                role=role,
                workstream=workstream,
                objective=objective,
                session_path=session_path,
                session=session,
                authority=authority,
                spawn=spawn,
            )
            if spawn and bundle is not None and session_path is not None
            else None
        )
        inactive_context_status = (
            "ALREADY_INTEGRATED"
            if already_integrated
            else "DEFERRED_BY_SPAWN_ROW_LIMIT" if deferred_by_limit else "NOT_SPAWNED"
        )
        roles.append({
            "index": index,
            "role": role,
            "purpose": role_pass.purpose,
            "required_by_kernel": role_pass.required,
            "spawn_intent": spawn_intent,
            "spawn": spawn,
            "spawn_reason": (
                "already_integrated"
                if already_integrated
                else f"deferred_by_spawn_row_limit_{spawn_row_limit}"
                if deferred_by_limit
                else "required_by_kernel"
                if role_pass.required
                else (f"optional_included_by_{spawn_policy}" if spawn else f"optional_skipped_by_{spawn_policy}")
            ),
            "spawn_deferral_reason": "deferred_by_spawn_row_limit" if deferred_by_limit else None,
            "completion_status": "ALREADY_INTEGRATED" if already_integrated else None,
            "completion_evidence": dict(completed_role_evidence.get(index, {})) if already_integrated else None,
            "carrier_slot": f"{carrier}_task" if spawn else None,
            "session_packet_path": _safe_relative(session_path, shell_root) if session_path is not None else None,
            "context_package_path": context_package["context_package_path"] if context_package else None,
            "compiled_context_bundle_path": context_package["compiled_context_bundle_path"] if context_package else None,
            "context_load_receipt_path": context_package["context_load_receipt_path"] if context_package else None,
            "context_load_contract": context_package["context_load_contract"] if context_package else inactive_context_status,
            "context_proof_return_gate": context_package["context_proof_return_gate"] if context_package else inactive_context_status,
            "template_action_return_gate": context_package["template_action_return_gate"] if context_package else inactive_context_status,
            "agent_context_system": context_package["agent_context_system"] if context_package else {"status": inactive_context_status},
            "context_system_read_paths": context_package["context_system_read_paths"] if context_package else [],
            "read_paths_ordered": context_package["read_paths_ordered"] if context_package else [],
            "required_context_missing": context_package["required_missing"] if context_package else [],
            "authority": authority,
            "return_contract": "proposal/evidence only until STEWARD integration; Task output must begin with ### CONTEXT PROOF and include ### TEMPLATE ACTION PROOF",
        })

    plan = {
        "schema_id": "ion.carrier_cycle_plan.v1",
        "created_at": _iso_now(),
        "carrier": carrier,
        "workstream": workstream,
        "objective": objective,
        "spawn_policy": spawn_policy,
        "spawn_row_limit": spawn_row_limit,
        "completed_role_indexes": sorted(completed_role_indexes),
        "completed_role_count": len(completed_role_indexes),
        "completed_role_evidence": {
            str(index): dict(evidence)
            for index, evidence in sorted(completed_role_evidence.items())
            if index in completed_role_indexes
        },
        "active_spawn_count": active_spawn_count,
        "deferred_spawn_count": deferred_spawn_count,
        "required_surfaces_ok": not bool(missing),
        "missing_required_surfaces": {role: [target.path for target in targets] for role, targets in missing.items()},
        "execution_bundle_root": _safe_relative(bundle.run_root if bundle is not None else execution_root_path, shell_root),
        "execution_bundle_materialized": bundle is not None,
        "trace_path": _safe_relative(bundle.trace_path, shell_root) if bundle is not None else None,
        "session_paths": [_safe_relative(path, shell_root) for path in bundle.session_paths] if bundle is not None else [],
        "handoff_paths": [_safe_relative(path, shell_root) for path in bundle.handoff_paths] if bundle is not None else [],
        "role_spawn_plan": roles,
        "next_lawful_action": "Execute only role session packets with spawn=true, in index order; do not infer additional roles from chat.",
        "production_authority": False,
        "live_execution_authority": False,
    }
    return plan


def validate_cycle_plan(plan: Mapping[str, Any]) -> tuple[bool, list[str]]:
    findings: list[str] = []
    for field in ("schema_id", "carrier", "workstream", "objective", "spawn_policy", "role_spawn_plan", "execution_bundle_root", "trace_path", "production_authority", "live_execution_authority"):
        if field not in plan:
            findings.append(f"missing:{field}")
    roles = plan.get("role_spawn_plan")
    if not isinstance(roles, list) or not roles:
        findings.append("invalid:role_spawn_plan")
    else:
        required_missing = [
            item.get("role")
            for item in roles
            if item.get("required_by_kernel")
            and not item.get("spawn")
            and item.get("completion_status") != "ALREADY_INTEGRATED"
        ]
        if required_missing and plan.get("spawn_row_limit") is None:
            findings.append(f"required_roles_not_spawned:{','.join(str(x) for x in required_missing)}")
        for item in roles:
            if item.get("spawn") and not item.get("session_packet_path"):
                findings.append(f"spawned_role_missing_session:{item.get('role')}")
            if item.get("spawn") and item.get("authority") in {None, "", "NOT_SPAWNED"}:
                findings.append(f"spawned_role_missing_authority:{item.get('role')}")
            if item.get("spawn") and not item.get("context_package_path"):
                findings.append(f"spawned_role_missing_context_package:{item.get('role')}")
            if item.get("spawn") and not item.get("compiled_context_bundle_path"):
                findings.append(f"spawned_role_missing_compiled_context_bundle:{item.get('role')}")
            if item.get("spawn") and not item.get("context_load_receipt_path"):
                findings.append(f"spawned_role_missing_context_load_receipt:{item.get('role')}")
            if item.get("spawn") and not isinstance(item.get("agent_context_system"), dict):
                findings.append(f"spawned_role_missing_agent_context_system:{item.get('role')}")
            if item.get("spawn") and item.get("agent_context_system", {}).get("status") == "active" and not item.get("context_system_read_paths"):
                findings.append(f"spawned_role_missing_context_system_reads:{item.get('role')}")
            if item.get("spawn") and item.get("context_load_contract") != "TASK_OUTPUT_MUST_BEGIN_WITH_CONTEXT_PROOF_AND_INCLUDE_TEMPLATE_ACTION_PROOF":
                findings.append(f"spawned_role_missing_context_proof_contract:{item.get('role')}")
            if item.get("spawn") and item.get("context_proof_return_gate") != "kernel.ion_context_proof_gate":
                findings.append(f"spawned_role_missing_context_proof_return_gate:{item.get('role')}")
            if item.get("spawn") and item.get("template_action_return_gate") != "kernel.ion_template_action_gate":
                findings.append(f"spawned_role_missing_template_action_return_gate:{item.get('role')}")
            if item.get("spawn") and item.get("required_context_missing"):
                findings.append(f"spawned_role_required_context_missing:{item.get('role')}:{', '.join(str(x) for x in item.get('required_context_missing', []))}")
    if plan.get("production_authority") is not False:
        findings.append("authority:production_not_false")
    if plan.get("live_execution_authority") is not False:
        findings.append("authority:live_execution_not_false")
    return (not findings, findings)


def write_cycle_plan(plan: Mapping[str, Any], root: str | Path | None) -> Path:
    shell_root = _resolve_shell_root(root)
    path = shell_root / ACTIVE_SPAWN_PLAN_RELATIVE_PATH
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(plan, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Build a deterministic ION role-cycle spawn plan from the sequential kernel.")
    parser.add_argument("--ion-root", default=None, help="Path to ION root or shell root containing ION/.")
    parser.add_argument("--carrier", default="cursor")
    parser.add_argument("--workstream", default="implementation", choices=[item.value for item in Workstream])
    parser.add_argument("--objective", required=True)
    parser.add_argument("--spawn-policy", default="required", choices=("required", "full", "objective"))
    parser.add_argument("--spawn-row-limit", type=int, default=None)
    parser.add_argument("--execution-root", default=None)
    parser.add_argument("--source-task", default=None)
    parser.add_argument("--write-current", action="store_true")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args(argv)

    plan = build_cycle_plan(
        args.ion_root,
        workstream=args.workstream,
        objective=args.objective,
        carrier=args.carrier,
        spawn_policy=args.spawn_policy,
        spawn_row_limit=args.spawn_row_limit,
        execution_root=args.execution_root,
        source_task=args.source_task,
    )
    valid, findings = validate_cycle_plan(plan)
    payload = {
        "verdict": "ION_CARRIER_CYCLE_PLAN_READY" if valid else "ION_CARRIER_CYCLE_PLAN_BLOCKED",
        "valid": valid,
        "findings": findings,
        "active_spawn_plan_path": str(ACTIVE_SPAWN_PLAN_RELATIVE_PATH) if args.write_current else None,
        "plan": plan,
    }
    if args.write_current:
        write_cycle_plan(plan, args.ion_root)

    if args.json:
        print(json.dumps(payload, indent=2, sort_keys=True))
    else:
        print(payload["verdict"])
        print(f"execution_bundle_root: {plan['execution_bundle_root']}")
        if args.write_current:
            print(f"active_spawn_plan_path: {ACTIVE_SPAWN_PLAN_RELATIVE_PATH}")
        for item in plan["role_spawn_plan"]:
            print(f"{item['index']}. {item['role']} spawn={item['spawn']} authority={item['authority']} session={item['session_packet_path']}")
        if findings:
            print("findings:")
            for finding in findings:
                print(f"- {finding}")
    return 0 if valid else 1


if __name__ == "__main__":
    raise SystemExit(main())
