-- Development/bootstrap seed for the ION operating runtime.
--
-- Apply only when intentionally recreating the manually bootstrapped demo state.
-- Do not treat these rows as accepted production state.

insert into ion_ops.automation_events (
  event_id,
  source_system,
  event_type,
  severity,
  carrier_id,
  carrier_type,
  agent_tag,
  branch_id,
  context_instance_id,
  packet_id,
  correlation_id,
  idempotency_key,
  title,
  summary,
  payload,
  evidence_refs,
  source_posture,
  accepted_state_claim,
  settlement_required
) values (
  '00000000-0000-4000-8000-000000000101'::uuid,
  'ion',
  'bootstrap_seed',
  'notice',
  'local_repo_seed',
  'local_codex_cli',
  'codex_local_ion_mason',
  'branch_seed_supabase_operating_runtime',
  'ctx_seed_codex_local_ion_mason_supabase_runtime',
  'PCKT-ION-SUPABASE-OPERATING-RUNTIME-BOOTSTRAP-001',
  'seed_ion_ops_bootstrap_001',
  'seed_ion_ops_bootstrap_001',
  'ION ops runtime bootstrap seed',
  'ION ops runtime bootstrap seed inserted from repo-managed seed file.',
  '{"seed": true, "production_authority": false, "accepted_state_claim": false}'::jsonb,
  '["supabase/seed/001_ion_ops_bootstrap_seed.sql"]'::jsonb,
  '{"source_type": "repo_seed", "accepted_state_claim": false}'::jsonb,
  false,
  true
) on conflict (event_id) do update set
  summary = excluded.summary,
  payload = excluded.payload,
  evidence_refs = excluded.evidence_refs,
  source_posture = excluded.source_posture,
  accepted_state_claim = false,
  settlement_required = true,
  updated_at = now();

insert into ion_ops.service_health_snapshots (
  snapshot_id,
  service_name,
  service_role,
  carrier_id,
  endpoint,
  host,
  port,
  status,
  verdict,
  version_line,
  production_authority,
  live_execution_authority,
  health,
  findings,
  source_posture
) values
  (
    '00000000-0000-4000-8000-000000000201'::uuid,
    'ION MCP preview',
    'mcp_http_preview',
    'ion_local',
    'http://127.0.0.1:8765/health',
    '127.0.0.1',
    8765,
    'unknown',
    'seed_only',
    null,
    false,
    false,
    '{"seed": true, "canonical_port": 8765, "accepted_state_claim": false}'::jsonb,
    '["Replace with live local service snapshot adapter output."]'::jsonb,
    '{"source_type": "repo_seed"}'::jsonb
  ),
  (
    '00000000-0000-4000-8000-000000000202'::uuid,
    'ION Action Gateway',
    'custom_gpt_action_gateway',
    'ion_local',
    'http://127.0.0.1:8777/health',
    '127.0.0.1',
    8777,
    'unknown',
    'seed_only',
    null,
    false,
    false,
    '{"seed": true, "canonical_port": 8777, "accepted_state_claim": false}'::jsonb,
    '["Replace with live local service snapshot adapter output."]'::jsonb,
    '{"source_type": "repo_seed"}'::jsonb
  ),
  (
    '00000000-0000-4000-8000-000000000203'::uuid,
    'ION local cockpit',
    'local_cockpit',
    'ion_local',
    'http://127.0.0.1:8788/health',
    '127.0.0.1',
    8788,
    'unknown',
    'seed_only',
    null,
    false,
    false,
    '{"seed": true, "canonical_port": 8788, "accepted_state_claim": false}'::jsonb,
    '["Replace with live local service snapshot adapter output."]'::jsonb,
    '{"source_type": "repo_seed"}'::jsonb
  )
on conflict (snapshot_id) do update set
  status = excluded.status,
  verdict = excluded.verdict,
  health = excluded.health,
  findings = excluded.findings,
  production_authority = false,
  live_execution_authority = false,
  updated_at = now();

insert into ion_ops.carrier_mount_receipts (
  mount_receipt_id,
  carrier_id,
  carrier_type,
  carrier_instance_id,
  agent_tag,
  conversation_tag,
  context_instance_id,
  branch_id,
  parent_context_id,
  current_packet,
  model_lane,
  loaded_refs,
  authority,
  write_scope,
  source_posture,
  return_target,
  persona_presentation,
  drift_findings,
  raw_receipt,
  accepted_state_authority,
  settlement_required,
  valid
) values (
  '00000000-0000-4000-8000-000000000301'::uuid,
  'local_repo_seed',
  'local_codex_cli',
  'local_dev',
  'codex_local_ion_mason',
  'supabase_operating_runtime_bootstrap',
  'ctx_seed_codex_local_ion_mason_supabase_runtime',
  'branch_seed_supabase_operating_runtime',
  null,
  'PCKT-ION-SUPABASE-OPERATING-RUNTIME-BOOTSTRAP-001',
  'local',
  '[{"path": "supabase/migrations/001_initial_ion_ops.sql", "source_type": "repo", "sha256": null}]'::jsonb,
  '{"production_authority": false, "live_execution_authority": false, "accepted_state_authority": false, "settlement_required": true}'::jsonb,
  '["supabase/", "ION/docs/setup/", "ION/02_architecture/"]'::jsonb,
  '{"repo_observed": ["supabase/migrations/001_initial_ion_ops.sql"], "user_reported": ["manual ion_ops bootstrap already exists"], "inferred": [], "accepted_state_claim": false}'::jsonb,
  '{"parent_lane": "operator_chat", "settlement_inbox": "ION/05_context/current/context_settlement/inbox/", "accepted_state_claim": false}'::jsonb,
  '{"persona_mounted": false, "presentation_mode": "receipt_only", "hidden_reasoning_exposed": false}'::jsonb,
  '[]'::jsonb,
  '{"seed": true, "accepted_state_claim": false}'::jsonb,
  false,
  true,
  true
) on conflict (mount_receipt_id) do update set
  current_packet = excluded.current_packet,
  loaded_refs = excluded.loaded_refs,
  authority = excluded.authority,
  source_posture = excluded.source_posture,
  return_target = excluded.return_target,
  persona_presentation = excluded.persona_presentation,
  raw_receipt = excluded.raw_receipt,
  accepted_state_authority = false,
  settlement_required = true,
  valid = true,
  updated_at = now();
